### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#103]
Plain and simple Footer component with links to MIT License, issue tracker for PostCSS and logotype for EvilMartians (mostly likely also hyperlink)

You can find all the necessary styleguide info from Zeplin - #98

**Comment by marcustisater** [comment]
![screenshot-footer](https://cloud.githubusercontent.com/assets/2952332/12494506/ceb04180-c08a-11e5-90f7-e4a83403d081.png)

**Comment by jeddy3** [comment]
I've made a start on this...
