### ISSUE TITLE
Evil Martians Logotype

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#104]
We need the logotype for EvilMartians, provide optimized svg and polyfill png

**Comment by MoOx** [comment]
png for real? Not sure that relevant these days... http://caniuse.com/#search=svg

**Comment by ai** [comment]
We have a special PostCSS to create PNF fallback. But I think it is not necessary.

**Comment by marcustisater** [comment]
Ok, skip PNG. Death to IE8 < ;)

**Comment by marcustisater** [comment]
My fault, the images can be sliced from the sketch files into SVGs directly. I did not know that. Thanks for  the input about the polyfil tho :)

#105
