### ISSUE TITLE
[Content Area] Built by community for community

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#106]
On the front-page there is a content area that has a section about "Built by community for community". We need someone to build the markup and apply some pretty css for that.

 You can find all the necessary styleguide info from Zeplin - #98

![screenshot-community](https://cloud.githubusercontent.com/assets/2952332/12494483/af78dd5e-c08a-11e5-9db7-10395e7bb81a.png)

**Comment by jeddy3** [comment]
I've made a start on this...

**Comment by marcustisater** [comment]
Great work once again.
