### ISSUE TITLE
Font Icon?

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#107]
There are some icons and small images shown in the mockup - What is you're guys recommendation of implementation these. Create an sprite sheet? Icon Font? just svg images?

Thanks for input.

**Comment by stephenway** [comment]
I lived through most of these options and eventually landed on the fact that I don't want to spend most of my time juggling icons, so I went with Material Icons webfont https://design.google.com/icons/

**Comment by MoOx** [comment]
Raw SVGs transformed as React SVG components. Incoming update for statinamic will include the appropriate transformation.

**Comment by MoOx** [comment]
For my concern, 99% of the time I use icons from http://iconmonstr.com/.

**Comment by marcustisater** [comment]
Aww man I have been wanting to test those out for ages. That might be worth a shot.

Thanks @MoOx for info

**Comment by stephenway** [comment]
> React SVG components

@MoOx Awesome!

**Comment by ai** [comment]
I am strongly against icons fonts, because there is no way to control their firm on every platform.

Also it is a hack. Font systems were created for fonts, but for icons.

SVG with postcss-inline-svg is simple and great for most cases.

**Comment by stephenway** [comment]
Actually you could say that webfonts are just an extension of glyph-based typefaces. But I agree it isn't the most native/pure way of using icons for web pages.

I'm all for anything that works, postcss-inline-svg looks good, haven't looked at it in a while.

**Comment by MoOx** [comment]
Inline SVG are far superior, you have a real control, can adjust the color using css fill property (works for multicolor svg too).

Since we are in React with webpack, we could do this

```js
import React, { Component } from "react"

import styles from "./index.css"
import SomeSVG from "../icons/some.svg"

export default class Footer extends Component {

  render() {
    return (
      <footer className={ styles.footer }>
          <SomeSVG />
      </footer>
    )
  }
}

```

**Comment by marcustisater** [comment]
Ah, that's really cool.

**Comment by ai** [comment]
@MoOx postcss-inline-svg allows you to set colors too. But CSS is better place to put presentation icons in terms of semantic.

Also CSS will be served from fast CDN. So putting SVG into static HTML will make them slower

**Comment by marcustisater** [comment]
I'd say we will focus on React SVG components for now and look at performance later. 

Thank you @MoOx
