### ISSUE TITLE
[Content Area] Showcase

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#108]
There is a content area on the front-page "Trusted by industry leaders". We need to apply markup for that. 

You can find all the necessary styleguide info from Zeplin - #98

![screenshot-showcase](https://cloud.githubusercontent.com/assets/2952332/12494632/a358f8f0-c08b-11e5-9337-56fe1f44536d.png)

**Comment by jeddy3** [comment]
I've made a start on this...
