### ISSUE TITLE
[Content Area] PostCSS in a nutshell

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#109]
There is a content area on the front page right under the mastheader about PostCSS in a "nushell". We would need to apply some markup and css for that. 

You can find all the necessary styleguide info from Zeplin - #98

![screenshot-postcss](https://cloud.githubusercontent.com/assets/2952332/12494750/4bcf2d88-c08c-11e5-813f-267bee1ac0b2.png)

**Comment by ai** [comment]
This control is not ready yet. We can't use switcher, because:

* Plugin description is very important, but here we will be forced to use small font and few lines of text.
* It is a main part of site. But we should force users to click to see full content.

**Comment by marcustisater** [comment]
Sorry, my fault. Let's leave it up for the designers to review it. 

@okonet had a new mockup in progress of this from #4 what I understand, correct?

**Comment by marcustisater** [comment]
resolved from latest in #4

**Comment by marcustisater** [comment]
![new](https://cloud.githubusercontent.com/assets/2952332/12536144/12806ee0-c29c-11e5-84d0-7a119311fec4.png)

**Comment by jeddy3** [comment]
I've made a start on this...

**Comment by marcustisater** [comment]
We added stylint as well.
