### ISSUE TITLE
Approach to device and browser compatibility

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss.org#113]
With the [basic structure underway](https://github.com/postcss/postcss.org/pull/112) (looking great btw!)... I think this is probably a good time to talk about device and browser compatibility, along with CSS techniques to achieve that compatibility.

The terminology around this issue is a [bit muddled](http://bradfrost.com/blog/post/the-many-faces-of-adaptive-design/), with the likes of: progressive enhancement, responsive web design, adaptive design, mobile-first, device-agnostic, pan-device etc meaning different things to different people. So, I'll try to keep it as simple as possible by asking a few questions (and offering up a few suggestions):

1. Is the intent to provide (within reasonable time and effort) the best experience possible irregardless of the browser and device the user has?

If so:

1. How can this be achieved across different viewport sizes? Perhaps vertically stacking everything _by default_, e.g. the items with the Navbar and Footer, and then, with the use of media queries, horizontally aligning the items of each component only when there is enough space to do so.
2. How can this be achieved across different input/interaction methods? Perhaps by ensuring the touch area for each link/button is large enough _by default_ to be easily tapped by a finger.
3. How can this be achieved across different screen resolutions?: Perhaps by using vector graphics as much as possible, `(r)em` units and [compressive images](https://www.filamentgroup.com/lab/compressive-images.html) for raster graphics. 

Any more?

And, if not (perhaps because it is not achievable within a reasonable amount of time and effort):

Scratch the above questions and suggestions :) Build the site for wide viewports _by default_ and serve this irrespective of the viewport size. Those users not using a wide viewport will just have to pinch-and-zoom.

What do y'all think?

**Comment by mxstbr** [comment]
Definitely going responsive, that shouldn't be a question nowadays. Strongly prefer vector and definitely using (r)em. Not yet sure how a11y will pan out as I'm quite bad at that, maybe somebody else has more experience with the pain points there?

As far as the mobile view goes, that should be decided by the designers. @okonet any input here?

**Comment by stephenway** [comment]
Might be easy to mark order on each object of the markup to show mobile order without reworking it into a mockup?

**Comment by mxstbr** [comment]
Not sure how that'd work, tbh. Order isn't really the important part, some parts might have to change appearance and things.

**Comment by marcustisater** [comment]
I agree with @mxstbr 

> Definitely going responsive, that shouldn't be a question nowadays. Strongly prefer vector and definitely using (r)em. Not yet sure how a11y will pan out as I'm quite bad at that, maybe somebody else has more experience with the pain points there?

I think we should consider creating a sketch for mobile.

**Comment by marcustisater** [comment]
btw great points @jeddy3 - I will definitely look into these more in depth.

**Comment by marcustisater** [comment]
@mxstbr do you think it's worth the effort to implement some of this to the [code guidelines](https://github.com/postcss/postcss.org/blob/master/CONTRIBUTING.md)?

**Comment by mxstbr** [comment]
Probably not a bad idea to put it in there!

**Comment by marcustisater** [comment]
Alright, cool. I figured that would the best scenario here otherwise it's difficult to keep on track with this for new developers. 

@jeddy3 - Would you like to try writing down some "ground rules" and check with @mxstbr to assist you?   :smile:

**Comment by jeddy3** [comment]
(Done in https://github.com/postcss/postcss.org/pull/148)
