### ISSUE TITLE
Property isolation

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#116]
Why we didn’t use `postcss-autoreset` to have isolated styles?

**Comment by MoOx** [comment]
My only concern with this: does this create like TONS of styles properties?
With CSS modules, I don't feel the need to use this plugin.

**Comment by ai** [comment]
@MoOx 

> With CSS modules, I don't feel the need to use this plugin.

CSS Modules and autoreset solves different tasks. Global CSS is not only about global selectors namespace. We still have global inteference between components.

For example, if we have a components: `<List><Item></List>` and in some point we put `line-height: 0` to `List` it will collapse the text inside `Item` too.

**Comment by MoOx** [comment]
Yeah, but that's the purpose of the C in CSS right?
Seems like a bit brutal :)

**Comment by ai** [comment]
@MoOx 

> does this create like TONS of styles properties?

It can create a one rule with all selectors if we will process a bundle through this plugin. Like:

```css
A, B, C {
    all: initial;
}
```

**Comment by ai** [comment]
@MoOx 

> Yeah, but that's the purpose of the C in CSS right?

Cascading should be explicit like:

```css
.item {
    font-size: inherit;
}
```

`inherit` value still works.

> Seems like a bit brutal :)

Many people told same about CSS Modules too ;).

**Comment by MoOx** [comment]
So if you have 150 selectors, the output is probably fun to see :)

**Comment by marcustisater** [comment]
Yeah, that's my only concern regarding this. The output :sweat_smile: Wouldn't that be huge?

**Comment by ai** [comment]
@marcustisater same as normalize.css. Plain CSS rules never is a problem for size. Anyway inline images will be the biggest thing.

**Comment by marcustisater** [comment]
I hear you, I'll leave this up for you experts to decide.

@mxstbr any input?

**Comment by mxstbr** [comment]
I think it'd be nice to use it, I've never worked with it but it sounds logical in combination with CSS Modules.

**Comment by marcustisater** [comment]
Alright, let's try it out. I'm up for it.

**Comment by MoOx** [comment]
I warn out, since we don't have a single CSS, output will be VERY redundant. Not a good idea imo.

**Comment by marcustisater** [comment]
I agree with you but let's try it out before excluding anything in advanced here

**Comment by marcustisater** [comment]
Not very necessary. Closing this one for now.
