### ISSUE TITLE
Established theme

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#117]
There has been some confusion regarding what the final design template looks like. Sorry, that is my fault. Anyway, we have two versions, one indiciets more for a light version and one more of a darker version. Right now, we have been moving on with the darker version but I would like to keep this open for a final decision. 

I am talking specifically about the theme and **NOT** the content. IMO the dark version looks the best, the colors are really good and creates an nice contrast. 

![03429518-c13c-11e5-9df3-86582a60604f](https://cloud.githubusercontent.com/assets/2952332/12536081/eb47aa70-c299-11e5-8ac1-644acfd8b660.png)

![7ec8106e-ba34-11e5-9a11-05ae598df809](https://cloud.githubusercontent.com/assets/2952332/12536091/2027421e-c29a-11e5-94f1-4d1e60186b01.png)

**Comment by marcustisater** [comment]
We need to improve the documentation for the design directory in the repository. I will help with that.

**Comment by marcustisater** [comment]
All generated sketch files will be in here - https://github.com/postcss/postcss.org/tree/master/design/src/template

**Comment by marcustisater** [comment]
@ai do you agree with the the dark version? I would like to close this one.

**Comment by ai** [comment]
Yeap, dark header is more cool and in right *black* magic spirit :D

**Comment by marcustisater** [comment]
Awesome, just a double check :smile: 

reopen if anyone thinks the lighter version is to take under consideration.
