### ISSUE TITLE
Sketch for front-page mobile viewport

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#118]
We need to create an sketch for how the front-page will look like on lower viewport sizes like mobile.

**Comment by marcustisater** [comment]
@okonet are you up for it? :smile:

**Comment by okonet** [comment]
I could do a quick sketch

**Comment by marcustisater** [comment]
Awesome, thank you. I think It would be easier for the developers to do mobile-first.

Yeah, quick sketch is great. We can always adjust details later.

**Comment by okonet** [comment]
I've just added the mockup for mobile version to Zeplin + updated a bit desktop version.

Please add me as a maintainer of this repo so I can push changes to the sketch file without going through (pointless) PRs. Thanks.

**Comment by marcustisater** [comment]
Great work, looking good.

You are already added to the maintainers file - should be working. https://github.com/postcss/postcss.org/blob/master/MAINTAINERS  - I will add you as a collab to the github repository as well so you have write access.

**Comment by okonet** [comment]
:+1: thanks it worked

**Comment by marcustisater** [comment]
Awesome, can you push it to the repo as well? I can generate the png if you would like to :smile:

**Comment by corysimmons** [comment]
Can I be added to Zeplin? Also, why is the design closed to begin with on an open project?

**Comment by marcustisater** [comment]
You are welcome to join us, we have a few sketches left that needs to be done and thought through so any help is good to combine ideas together. 

Unfortunately, Zeplin dosen't allow to make it public so we will have to invite people by request. You can start by reading [here](https://github.com/postcss/postcss.org/tree/master/design).

I am going to update the documentation more in detail, might be all a little bit fuzzy. Let me or @stephenway if you want in to Zeplin.

Thanks!

**Comment by corysimmons** [comment]
Eh, it's alright. It might be nice to have a "Current Mockups" Issue where you just paste a screenshot in every now and then so the community can kinda see what's going on without having to get a Zeplin account and be manually added to the group.

It'd be nice if the community could at least watch the progress y'know?

**Comment by marcustisater** [comment]
I hear you, will definitely consider doing something like that. We do have an [public url](https://scene.zeplin.io/project/56a3fb9180974a77015a1c2b) for the Zeplin project and also some [documentation](https://github.com/postcss/postcss.org/tree/master/design) 

The reason why we moved forward so quickly with finalizing the mockup is to keep activity going with this project, it's very common that a lot of people will drop out when there is a slow paste...

Thank you for the input.

**Comment by marcustisater** [comment]
We did send out a tweet the other day https://twitter.com/PostCSS/status/693169287339577344 that attracted some more people checking out this repo.

**Comment by corysimmons** [comment]
Ah okay cool. So you guys can update that Zeplin public facing page as much as you want? Could you add a few more screenshots in there or is this homepage design all that we've got right now?

**Comment by marcustisater** [comment]
We only have the homepage ready for development. 

If you would like to help out there is #119 and #120 to start working on that is a little bit tricky. I think you should grab one of those issues :wink:

**Comment by corysimmons** [comment]
Nah, I'm too busy. I'll shut up and leave you guys alone. Best of luck

**Comment by marcustisater** [comment]
@okonet sorry for repeating - Would you mind uploading the sketch file to the repository so can sync everything together.

Thanks!

**Comment by okonet** [comment]
I did a few days ago.

**Comment by marcustisater** [comment]
Are you sure? 

I'm not talking about Zeplin - https://github.com/postcss/postcss.org/tree/master/design/src/sketch

**Comment by okonet** [comment]
Damn, I pushed to my fork. Will do a PR right now.

**Comment by okonet** [comment]
@marcustisater https://github.com/postcss/postcss.org/pull/141

**Comment by marcustisater** [comment]
Yeah that's probably why, no worries. You can just push it right through master, I can generate the png through gulp.

**Comment by okonet** [comment]
I've just updated. PR had too many conflicts because of dirs structure

**Comment by marcustisater** [comment]
Thanks!

**Comment by marcustisater** [comment]
hey btw Andrey, when you have time to look through the website and see if you can catch any minor bugs - report them in #140
