### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#12]
Design to be made when #4 is completed.

**Comment by stephenway** [comment]
I'm interested in helping with this. Already started a mockup but would like to also talk about strategy.

**Comment by marcustisater** [comment]
Awesome, yeah we definitely have to discuss strategy before moving forward with a full visual design.

**Comment by MoOx** [comment]
I think the design should be made with small PRs. That's imo the best way to get quick feedbacks.

**Comment by marcustisater** [comment]
Agreed, that would be more efficient in this case.

**Comment by DaZzz** [comment]
Ready to help. :shipit:

**Comment by stephenway** [comment]
## Templates
* docs
* plugin list
* wizard/generator/etc

**Comment by marcustisater** [comment]
@stephenway - I think this should stay as a "meta" issue.

We would need to split upp design into custom layouts, basic articles, pages, landing-pages, plugin-search etc...

**Comment by stephenway** [comment]
Agreed
