### ISSUE TITLE
Sketch for style guide

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#121]
I am going to be helping out creating the styleguide #15 but I would need to know all the essential parts for it therefor I think it's a good idea to create somewhat of a sketch file for that first.

@okonet - What do you think?

**Comment by okonet** [comment]
I'd prefer to have a styleguid done with something like https://github.com/sapegin/react-styleguidist not Sketch. Sooner we switch to writing modules with CSS is better IMO. I think Sketch file should act more as a initial guide to design.

**Comment by okonet** [comment]
I see now react-styleguidist was already mentioned in #15. :+1:

**Comment by marcustisater** [comment]
Yeah, I started looking into styleguidist, it's really good. Thanks for you're input, it makes sense.
