### ISSUE TITLE
Suggestion for indiviual plugin pages

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#122]
I've been focusing a lot internally of content strategy and site mapping #83 especially now on the plugin parts.

**I have an suggestion:**
What do you guys think of individual plugin pages were there would be a short introduction of what the plugin does, links to GitHub, npm etc. It would be more a organized overview.

This most likely wont work in the long run because there is way to many plugins to cover but it could be a suggestion for featured plugins. Suggestion? What's best? Forward link to github only?

Thanks for input.

**Comment by marcustisater** [comment]
@ai what do you think? Do you want me to rephrase the question?

**Comment by ai** [comment]
Hm. Looks good for me. But what is a benefit of this pages to our users?

**Comment by marcustisater** [comment]
The point of it is not to make it "scary" for new users to PostCSS by forwarding them directly into an GitHub repository. I'm picturing an nice organized page with some introduction-text on what the plugin does and how to install it with links to GitHub, npm etc.

Let me quickly sketch something for you.

**Comment by TrySound** [comment]
Maybe generate these pages from plugins readme? One more reason to write good readme :)

**Comment by stephenway** [comment]
When I am thinking about npmjs.org's project pages, I think they seem unnecessary as a subset on-top of Github, so my question would be, what's the value our users would be getting out of individual plugin pages?

**Comment by marcustisater** [comment]
The whole point of it is to give the user an more ease-in introduction to the PostCSS plugin instead of instantly throwing it over to GitHub repository which can be scary for some people that are new to this. The value is basically to make it more user friendly then what GitHub is. 

@TrySound: Yeah definitely could be a good option. 

Is it just me that think this is might work out? Otherwise I think an GitHub hyperlink is fine.

**Comment by marcustisater** [comment]
Closing this one. Bad idea for now 😄
