### ISSUE TITLE
Webfont

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#129]
@ai is it correct that we are using Franklin Gothic Book as the official webfont for the website?

**Comment by MoOx** [comment]
You cannot according to the license I think. It's just for the logo.

**Comment by marcustisater** [comment]
Yeah that's why I got confused, read https://github.com/postcss/brand/issues/9

**Comment by ai** [comment]
Yeap, we can’t use Franklin Gothic Book

**Comment by marcustisater** [comment]
My fault, didn't read through the entire issue.

**Comment by marcustisater** [comment]
so the decided is Kreon @ai ? I want to double check.

**Comment by ai** [comment]
Kreon is a logo type. Not for average text. PT Sans, Ubuntu is good for plain text.

**Comment by marcustisater** [comment]
Alright, I have to regroup with Stephen and Andrey to figure out their thoughts about this so we can get a styleguide going as well.

**Comment by okonet** [comment]
Just FYI all designs are using [Fira Sans](https://www.google.com/fonts/specimen/Fira+Sans) and [Merriweather](https://www.google.com/fonts/specimen/Merriweather)

**Comment by stephenway** [comment]
Actually I was going to ask, why we are using so many fonts?

**Comment by okonet** [comment]
You mean 2? I don't think this qualifies as "too many" :)

**Comment by marcustisater** [comment]
I agree, two fonts is enough. Thanks for update @okonet

**Comment by stephenway** [comment]
Yea 2 isn't a lot, but the sketch file is using at least 4 different weights among those 2.

**Comment by okonet** [comment]
@stephenway I assume you're concerned about the download size? I think this can be optimized and reduced to 2 weights.

**Comment by stephenway** [comment]
@okonet Sounds good!

**Comment by marcustisater** [comment]
Great. How can we make it 100% clear for designers and developers that these are the fonts, colors that's the way to go. 

Styleguide? Zeplin.io? Documentation in [design](https://github.com/postcss/postcss.org/tree/master/design)? 

What do you guys think @okonet, @stephenway ? What's the best approach?

**Comment by stephenway** [comment]
For now I'd stick with the zeplin styleguide as that has the most information ATM

**Comment by marcustisater** [comment]
Yeah figured, styleguide is later formed.

**Comment by marcustisater** [comment]
Thanks for the update @okonet, I should have seen it right away from the sketch.

**Comment by marcustisater** [comment]
#86
