### ISSUE TITLE
[meta] Front-page

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#132]
Meta ticket of front-page for better overview

~~#118 - Sketch for mobile~~
~~#106 - Built by community for community~~
~~#108 - Showcase~~
~~#109 - PostCSS in a nutshell~~
~~#102 - Header~~
~~#103 - Footer~~

**Comment by jeddy3** [comment]
I've made a start on these... I'll hopefully have something to show in a day or two.

Just wanted to give you all the heads up so that we don't duplicate effort :)

**Comment by marcustisater** [comment]
That's awesome to hear, I'm glad you picked it up. I know @mxstbr is starting next week with the development but the only thing we have to go on is the home page so let's make that top notch until we have some more sketches.

Looking forward for PR :smile:

**Comment by jeddy3** [comment]
I know @mxstbr has been busy working with @MoOx in evolving the `statinamic` tool, which is a little beyond my JavaScript skills. So I figured I'd help out with something I do know... CSS and HTML :)

**Comment by MoOx** [comment]
(Btw, I am currently working on a huge update for statinamic - which take times but which will make things way better on many points ^^)

**Comment by marcustisater** [comment]
That's great to hear.

**Comment by marcustisater** [comment]
Great work @jeddy3
