### ISSUE TITLE
Increase font

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#138]
Guy, having a first preview is awesome. Great work.

Just a small notice: we should increase font size in plugin description and “Your company is using PostCSS? Let us know!”.

**Comment by jeddy3** [comment]
They are currently 13sp. I'll bump it to 14sp as that'll be inline with [Google's recommended minimum](https://www.google.com/design/spec/style/typography.html#typography-styles) for body text. Sound good?

**Comment by marcustisater** [comment]
also worth mentioning #129 ref #86

**Comment by ai** [comment]
14px is a smallest font size that I use. Why not 16px?

I think bigger font (at least under 32px) is always better. Many people have bad screens. More people have short-sightedness. Even if you have ideal eyes, you will read small text slower.

**Comment by jeddy3** [comment]
> 14px is a smallest font size that I used. Why not 16px?

I'm not sure why 14px is Google's recommended font size for small screens. I suspect it has something with [uncomfortable line lengths](https://www.google.com/design/spec/style/typography.html#typography-other-typographic-guidelines) when it's any bigger.

As we're trying to pick a font size that works across all viewport sizes (to save us a ton of effort) perhaps we can try 16px as a compromise between short line lengths in narrow viewports and too small text in wider ones? I'll create a PR so we can all see :)

**Comment by okonet** [comment]
I think we can close this one after #153 is merged.

**Comment by marcustisater** [comment]
Hmm, yeah. I would need to double check however, the font-sizes seems off comparing to the sketch you made.

**Comment by okonet** [comment]
LGTM
