### ISSUE TITLE
[meta - bugfixes] for prio launch 1.0

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#140]
As sure many of you know, we have the home page up and running on `postcss.org`. We are going to keep it very lightweight now for a soft launch instead of tackling on #119. I rearranged the [**milestone 1.0**](https://github.com/postcss/postcss.org/milestones/1.0)

but there are a lot of **voices** so I would like to keep them in this issue or create new once referenced to this to prioritize bug fixes for 1.0 

The first thing I think we have to fix is the reloading bug of Statinamitc #94 - that's assigned for @MoOx to update.

**Comment by marcustisater** [comment]
#139 

#138

**Comment by okonet** [comment]
Also #145

**Comment by marcustisater** [comment]
Alright, no more bug reports for 1.0 launch, rest will be sent to 1.1
