### ISSUE TITLE
Visual updates

### ISSUE THREAD

**Issue by okonet** [postcss/postcss.org#145]
I've just checked the latest version from master. Amazing work!

I've spotted a few issues though:

1. The logo looks much smaller as on mockup making look unproportional to the text and other elements. See side-by-side comparsion.

![2016-02-02 at 19 08](https://cloud.githubusercontent.com/assets/11071/12759244/57188826-c9e0-11e5-9fd8-fe72a7b9f52a.png)

2. The PostCSS text with 2 colors doesn't look great to me. Also the red color differs from the logo ones.
Logo: `#dd3a0a` Text: `#dd3735`. I'd stick with the white color tho.

3. I think we could try serif font for paragraphs text. And yeah, it should be bigger (#86)

I could do some visual tweaks myself soon.

**Comment by mxstbr** [comment]
:+1: Agree with the PostCSS in only one color, looks better to me too!

**Comment by ai** [comment]
:+1:

**Comment by marcustisater** [comment]
I agree with all of the points listed, PR's welcome.

**Comment by jeddy3** [comment]
> I could do some visual tweaks myself soon.

Fantastic. It would be awesome if you could pick this up as you've got the eye to make the tweaks :) 

I'll then be able to make time to document the CSS conventions.

> The logo looks much smaller as on mockup

Yep, I wasn't able to extract the logo from the .sketch file—I think I was missing a font or something—and so I quickly grabbed the most similar one I could find from https://github.com/postcss/brand. Can you replace it please? One thing to keep in mind is that I've, so far, committed only _optimised_ svgs to the repo and so, if possible, can you run the logo through SVGO (perhaps via https://jakearchibald.github.io/svgomg/) before you commit it.

**Comment by stephenway** [comment]
@jeddy3 I'll update the brand and run it through our svgo task tonight.

**Comment by okonet** [comment]
> One thing to keep in mind is that I've, so far, committed only optimised svgs to the repo and so, if possible, can you run the logo through SVGO (perhaps via https://jakearchibald.github.io/svgomg/) before you commit it.

This should be automated and done in a pre-commit hook.

**Comment by marcustisater** [comment]
I replaced the logotype with this [one](https://github.com/postcss/brand/blob/master/dist/postcss-logo-vertical-white.svg). If you look closely at the home-page sketch file the logotype actually looks way bigger and also more "centered" with the hero background image. I'm refereeing to the circle. 

@okonet: Don't you think we should go with the web fonts that you guys defined (#129)?

**Comment by okonet** [comment]
We should use the logo from the sketch. But without the type part. 

I would try using web fonts. I think they will improve the feel a lot.

**Comment by marcustisater** [comment]
Yeah, let's try that instead.

I'll get that up asap. Thanks for input.

**Comment by marcustisater** [comment]
I added the web fonts now as well, I have to double check all the font-sizes as well. They seem off now.

**Comment by okonet** [comment]
I think everything was addressed in https://github.com/postcss/postcss.org/pull/153 and in https://github.com/postcss/postcss.org/pull/154.

**Comment by marcustisater** [comment]
Yeah, I will close this one. If you have any more visual adjustments to be made, add them to a new issue for that.
