### ISSUE TITLE
Automatically optimize images and SVGs in pre-commit hook

### ISSUE THREAD

**Issue by okonet** [postcss/postcss.org#146]
This is a follow up for this note:

> I've, so far, committed only optimised svgs to the repo and so, if possible, can you run the logo through SVGO (perhaps via https://jakearchibald.github.io/svgomg/) before you commit it.

that came from #145

**Comment by jeddy3** [comment]
:+1:  :)

**Comment by marcustisater** [comment]
Awesome, I totally forgot about that. 

Side note: The PostCSS logo is in the [brand repository](https://github.com/postcss/brand) for PostCSS, we should do a similar thing over there.

**Comment by stephenway** [comment]
We are, with the `gulp minify` task, just need to add it to the main pre-commit task.

**Comment by MoOx** [comment]
That might help https://www.npmjs.com/package/ghooks

**Comment by marcustisater** [comment]
Thanks @MoOx - I can try get this going this week.

**Comment by okonet** [comment]
I'm on it. No worries.

**Comment by okonet** [comment]
BTW should we use a webpack loader for that instead? Or pre-commit hook is more explicit?

**Comment by MoOx** [comment]
The simpler solution (and more portable) is to avoid webpack when possible but that's not always relevant.
