### ISSUE TITLE
Name for webpack logo

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#147]
We have a webpack in PostCSS users. This logo have no project name. But many people can miss that it is webpack logo.

**Comment by mxstbr** [comment]
We could use this: https://github.com/webpack/webpack.github.com/blob/master/assets/logo-vertical-quadratic.png

**Comment by marcustisater** [comment]
To be honest, I think we need to reconsider this section. It's a mix between companies and open source projects, on the bottom of that section it says "_Is your company using PostCSS?_" 

Maybe we can split this up into two sections were we could one section showing "**It's easy to add**" showing build tools like Grunt,Gulp,Brocolli and Webpack and the other section for "**Using PostCSS**" known companies like Google, Automattic, Taobo etc.

**Comment by ai** [comment]
Yeap, let's also change other text. But anyway we will have logos, because they are largest.

**Comment by okonet** [comment]
We could use [JetBrains](https://www.jetbrains.com/) logo. I can get us a permission. WYT?

**Comment by ai** [comment]
@okonet wow, where they use PostCSS

**Comment by okonet** [comment]
I think all their web projects uses it.

**Comment by ai** [comment]
@okonet can you ask your friend in JetBrains? We should be 100% sure.

**Comment by okonet** [comment]
@Leonya gave me persmission to use it. I still could get an official one.

**Comment by marcustisater** [comment]
That would be awesome.

@okonet what do you think about splitting these sections up into two? One for companies and the other for the build tools. Does it make sense for the design?

**Comment by marcustisater** [comment]
quick solution for now would be to switch out Webpack logo for JetBrains.

**Comment by okonet** [comment]
I'd put build tools into separate page (Installation & Setup) and just remove the Webpack logo from the front page.

**Comment by ai** [comment]
I think webpack is more recognizable than JetBrains. Maybe we should put 5 logos.

**Comment by mxstbr** [comment]
Woah JetBrains uses PostCSS? Awesome!

**Comment by marcustisater** [comment]
Alright, fair enough. I'd say remove webpack for JetBrains logo. We should still keep the site clean looking and not adding in to many logotypes.

**Comment by princed** [comment]
Hi, guys :)
Here is the an [svg](https://github.com/postcss/postcss.org/files/118871/jetbrains.svg.zip) for you.

**Comment by marcustisater** [comment]
Thank you very much @princed, I can add that tonight.

Should I replace the webpack logo or add it as the fifth one @ai ?

**Comment by ai** [comment]
I think we should add JetBrains logo as fifth and update webpack logo with project name.

Webpack is much more recognizable than JetBrains in my option.

**Comment by marcustisater** [comment]
Sure, but as I said before - Webpack is not a company, it can be a little confusing when the text under says:

_"Is you're company using PostCSS?"_

I will add the webpack logo with text and JetBrains.

**Comment by ai** [comment]
Let's just change text to fix it 😀

**Comment by marcustisater** [comment]
Ok, I can figure something out.

**Comment by okonet** [comment]
Thank you @princed!

I agree with @marcustisater we should not include webpack logo in this section.

**Comment by ai** [comment]
@okonet why you think to remove weback if we will rename section title?

**Comment by okonet** [comment]
To what? And in this case we should add logos of grunt and gulp as well, right?

**Comment by okonet** [comment]
TBH I think having some big companies and not build tools is good for markting. I'd even ask for more big names (Facebook, Airbnb, etc.). I think we could reach a few dev from these companies on twitter. WYT?

**Comment by ai** [comment]
@okonet nope, webpack uses PostCSS in default `css-loader`. Webpack by default need to process `@import` and `url()`. Also `css-loader` contains CSS Modules features. And this is why webpack uses PostCSS inside.

So every webpack users uses PostCSS. This is why its logo is so important.

**Comment by okonet** [comment]
Sorry, but I'm still not convinced and I think this is very technical explanation. For "normal" developers out there it probably won't ring a bell. Google as company will.

**Comment by okonet** [comment]
Don't get me wrong. I want to emphasise that Webpack uses PostCSS under the hood. But for the front page I think it's more important to have some big companies. Anyway it's your call and I'm okat with chaning the title if you see more value in that.

**Comment by marcustisater** [comment]
Well said @okonet. I think we should take the Webpack logo under another section with Gulp & other build tool friends and split up into two sections as mentioned earlier. 

We should really embrace Webpack being under the hood of PostCSS but that wont ring the bell to the visitor without **knowing** about it at first. It wont make sense. We have to "explain it".

**Comment by marcustisater** [comment]
@ai let's start with this and if you have a super bad feeling about it, we can add webpacks logo back.

**Comment by ai** [comment]
OK, let’s remove webpack ;)

**Comment by marcustisater** [comment]
:smile:
