### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by halvves** [postcss/postcss.org#156]
I just forked/cloned and was poking around and noticed that there isn't a [404 page set up](https://help.github.com/articles/custom-404-pages/) for gh-pages.
![gh-pages 404 page](https://cloud.githubusercontent.com/assets/9411730/12939865/b016454a-cf89-11e5-90ac-f64e58a06412.png)

The non-hosted local version shows a little bit of a 404 page, but could still use some tweaking (and setting up to work on gh-pages).
![local dev 404 page](https://cloud.githubusercontent.com/assets/9411730/12939927/295b017a-cf8a-11e5-8635-112520a4b7b1.png)

I'm not sure if this is something that you would want or not before go live for v1. It certainly helps portray an attention to detail and a professional experience.

P.S. - I know that I'm new to project. I've dipped around the docs and the contribs file, but please do let me know anything I can do to help. I'm new to react/statinamic, but am reading up on their docs and studying the source of the site

**Comment by MoOx** [comment]
Blocked by https://github.com/MoOx/statinamic/issues/47

**Comment by MoOx** [comment]
(It's on my todo, I have this issue on multiple sites).

**Comment by marcustisater** [comment]
Howdy @halvves, thanks for joining in and submitting an issue. I hope the docs helped you get started. I totally forgot about the 404-page and I think we should prioritize this for 1.0 too, as you said it's a better for user experience. 

@MoOx - That's great, if we can get this done with #94 that would be great. Isn't it possible to create a "temporary" routing for this for right now?

@halvves if you would like to help with the 404-page, you can start by creating a component for it or create a quick sketch of how you think it should look like, don't hesitate to ask for help.

**Comment by marcustisater** [comment]
I'm going to prioritize this for 1.0 and help but if we can't make time for it depending on  https://github.com/MoOx/statinamic/issues/47 - We can add it later.

**Comment by MoOx** [comment]
@marcustisater using a `<Route>` will make this work during client navigation only (so after one successful page). I will try to handle this asap.

**Comment by marcustisater** [comment]
Ok, thats makes sense. @halvves let me know if you are up doing some markup and styles once @MoOx is completed with https://github.com/MoOx/statinamic/issues/47

**Comment by halvves** [comment]
@marcustisater - Certainly. Would you want that as just a hard coded component for now, like the components on the index? Or should there be a markdown file for the 404 text?

**Comment by MoOx** [comment]
Component is a better idea (for client side 404).

**Comment by MoOx** [comment]
[Statinamic 0.8 can now handle that.](https://github.com/MoOx/statinamic/blob/master/CHANGELOG.md#080---2016-02-24). There is an example for the upgrade and if you check the boilerplate (or docs) you will find a 404.md example and a PageError component that should help.

**Comment by halvves** [comment]
Brilliant work. I've been lurking the progress of the v0.8 release. I'll go ahead an implement this this evening (Central Standard Time).

**Comment by marcustisater** [comment]
@halvves are you still up for creating the 404 page? Keep in mind that there is no pressure or deadline :smile: 

Take you're time.

**Comment by halvves** [comment]
@marcustisater - definitely up to. things picked up with the day job and some after hours projects for a while, but hopefully i'll find some time for it soon!

**Comment by marcustisater** [comment]
That's great to hear, I just wanted to check-in for status report. If work gets too overwhelming for you, just give me a heads up and I will leave this up for grabs.

**Comment by marcustisater** [comment]
[From](https://github.com/postcss/postcss.org/issues/156#issuecomment-188251200) #190 we added the ErrorPage component but it still need some love. I will leave the rest up for you @halvves :smile:

**Comment by Vall3y** [comment]
Hi, I have picked off from where you started at PR #205

**Comment by marcustisater** [comment]
That's good enough for now, bump back if we have some more design changes.

Thanks for the PR @Vall3y

**Comment by halvves** [comment]
@marcustisater, sorry I dropped the ball on this one. all of my other obligations have picked up like crazy. @Vall3y, thanks for stepping in!
