### ISSUE TITLE
Replace user pics with GitHub's versions

### ISSUE THREAD

**Issue by okonet** [postcss/postcss.org#160]
ATM the user pics for the OSS section are from http://uifaces.com (down at the moment of writing). We should replace those images with the real contributors' userpics from GitHub. 

Initially my idea was to fetch them from GitHub servers (using API). Not sure how this result in the overal loading performance tho. So this could be worth experimenting with.

**Comment by ai** [comment]
BTW, maybe real photo from PostCSS meetups are more “warm” and “real”?

**Comment by okonet** [comment]
Initially I wanted to create a component that scrolls through all the contributor's faces. So everyone is on it. I think meetup photos are neat, but far from including everyone.

**Comment by okonet** [comment]
But we could try this as well, of course.

**Comment by marcustisater** [comment]
Hmm, not sure if we can prioritize this for milestone [1.0](https://github.com/postcss/postcss.org/milestones/1.0) but I agree, we should have the real contributors on that image.
