### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#161]
I think every site should have favicon

**Comment by ai** [comment]
I think this issue is related https://github.com/postcss/brand/issues/8

But we can use current logo as first version of favicon too

**Comment by okonet** [comment]
:+1:

**Comment by marcustisater** [comment]
@stephenway will make one for the first release.

**Comment by ai** [comment]
Maybe we should put any favicon right now and change it to good version later? Missed favicon is not cool for modern sites :).

**Comment by ai** [comment]
Any updates? Should we put just a automatically converted favicon?

**Comment by stephenway** [comment]
I'm overloaded right now, maybe just proceed with something scaled for now.

**Comment by marcustisater** [comment]
I'll make room for it - I will just use the logo for now.

Should I generate one from http://realfavicongenerator.net/ or is 16x16 good enough for now?

**Comment by ai** [comment]
We need only 16x16, 32x32 and 192x192.

Abd we can miss 16x16 if we just downscale it from 32x32.

**Comment by marcustisater** [comment]
Ok, thanks.

**Comment by marcustisater** [comment]
I added some initial ones just for now #193
