### ISSUE TITLE
Social meta tags

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#162]
We need better OpenGraph and other social media tags. At least we need a tag with image for OpenGraph tag.

**Comment by ai** [comment]
Think we should use big black image with red logo from header for OpenGraph.

**Comment by halvves** [comment]
Do we have a larger version of the dark bg image (alchemy.*)? I've found larger versions of the source image, but those obviously aren't the right color/style.

I have a preliminary 400x400 og image ready, but a [1200x1200 would be nicer](http://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit).

![postcss-og](https://cloud.githubusercontent.com/assets/9411730/13013991/61678054-d177-11e5-95b9-af5b5bc57572.png)

**Comment by ai** [comment]
I think @okonet has source

**Comment by okonet** [comment]
@halvves sketch file has it as well. Is there any documentation on sizes etc for OpenGrpah? I could add an artboard for that to Sketch.

**Comment by ai** [comment]
Yeap, image sizes is tricky :)

**Comment by halvves** [comment]
@okonet Here are [Facebook's official recommendations regarding og:image](https://developers.facebook.com/docs/sharing/best-practices#images).

The link in my comment above explains how to satisfy Facebook's recommendations as well as have decent square images for reddit shares, etc.

**Comment by ai** [comment]
So we need `1200 x 630`

**Comment by ai** [comment]
So, if we take 1200 × 1200 it will be cutted in facebook to 1200 × 630?

**Comment by okonet** [comment]
`-rw-r--r--  1 okonet  staff   271K 12 Feb 18:55 opengraph@2x.jpg`

Are we sure we want 2× resolution?

**Comment by okonet** [comment]
I can reduce the quality of JPG to 40% (since it's a 2x image anyway). In this case it will be ~140KB — still a lot IMO.

**Comment by ai** [comment]
`1200 × 1200` is already for HiDPI screens

**Comment by halvves** [comment]
@marcustisater, @okonet  - it seems both myself and the article that I had referenced were wrong in stating that Facebook would crop from both the top and the bottom. we may just want to stick to Facebook's suggested size. My apologies.

![og-crop-ex](https://cloud.githubusercontent.com/assets/9411730/13026117/68fd38fc-d1e2-11e5-896b-def294e64835.png)

**Comment by halvves** [comment]
Also. It appears that Facebook might be having trouble reading the current og:image meta tag.

Quoted from the from the [Facebook linter](https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Fpostcss.org):

"og:image could not be downloaded or is too small

og:image was not defined, could not be downloaded or was not big enough. Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook. Image 'http://postcss.org/_/web_modules/App/opengraph@2x.jpg' will be used instead. Consult http://developers.facebook.com/docs/sharing/webmasters/crawler for more troubleshooting tips."

**Comment by halvves** [comment]
@okonet  1200 x 630 is Facebook's official recommendation that we should have listened to. My silly idea was wrong. Also we may want a file name that doesn't have '@' or other similar chars in it. The scraper seems to be having trouble fetching the image due to strange chars/html  escapes.

**Comment by marcustisater** [comment]
resolved from #176
