### ISSUE TITLE
Horizontal scroll on mobile

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#163]
![9ziqxkobmes](https://cloud.githubusercontent.com/assets/19343/13009295/cab8d2f8-d1ac-11e5-900a-4eabee12f04d.jpg)

**Comment by marcustisater** [comment]
hyphens maybe? I'll fix that. I'm doing font adjustments at the moment.

**Comment by marcustisater** [comment]
Is the horizontal scroll still there? I think it got resolved from an earlier issue otherwise I'll looking into it.
