### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#166]
I create a Google Analytics account. Here is a tracker code:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73693753-1', 'auto');
  ga('send', 'pageview');

</script>
```

/cc @marcustisater

**Comment by ai** [comment]
Analytics will be useful for example for countries statistics. Or for conference talk efficiency feedback.

**Comment by marcustisater** [comment]
Sure thing.

**Comment by ai** [comment]
If you want a access to analytics, please provide a email here.

/cc @ben-eb @okonet

**Comment by halvves** [comment]
Me being new to the react world... is this just a matter of including the analytics script or do we need to employ something like [react-ga](https://github.com/mozilla/react-ga)?

**Comment by marcustisater** [comment]
@MoOx /@mxstbr - any recommendations? Thanks!

**Comment by MoOx** [comment]
https://github.com/MoOx/statinamic/blob/master/docs/web_modules/GoogleAnalyticsTracker/index.js

**Comment by MoOx** [comment]
Maybe I should add this in the default boilerplate...

**Comment by MoOx** [comment]
(Yeah poke me when needed, I unwatched because of too many activity ^^)

**Comment by marcustisater** [comment]
Awesome, that's what I was looking for. @halvves do you want to give it a shot? 

@MoOx haha, just tell me when I get to annoying, I don't want to be up you're ass :smile: and yeah you should definitely add it to the boilerplate imo.

**Comment by MoOx** [comment]
No problemo. It's fine.

Here is the usage https://github.com/MoOx/statinamic/blob/813aafc3b32608a7281270610905f4000e95f133/docs/web_modules/LayoutContainer/index.js#L29
