### ISSUE TITLE
Evil Martians badge don’t match the pixel grid

### ISSUE THREAD

**Issue by romashamin** [postcss/postcss.org#170]
![postcss-website-em-badge](https://cloud.githubusercontent.com/assets/1148914/13012475/79fd14f4-d1bc-11e5-8222-967b872543ed.png)

**Comment by marcustisater** [comment]
Thank you @romashamin for reporting this in.

**Comment by marcustisater** [comment]
Sorry for delay, #188 will resolve this issue.
