### ISSUE TITLE
Convert absolute font-sizes to relative

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#174]
Everything seems to be added with pixels, we should consider doing it in rems.

**Comment by mxstbr** [comment]
:+1: Sounds like a good idea.

**Comment by maxshearer** [comment]
I could have a go at this at some point soon.

It's probably worth discussing what the benefits of using rems over pixels in this case are though. As far as I can work out (correct me if I'm wrong) there's currently no media queries in any `html` rule so using rems would make little difference at the moment.

Is the plan to do implement them now, adding some sort of responsive typography at a later date?

**Comment by marcustisater** [comment]
Yeah, that's the plan but it's some what of a bigger refactoring. I think we had this discussion before but can't remember the issue number. 

The benefits of using `rems/ems` is that it's relative and can change the entire typography font-size "flow" and adjust it one place depending on a media query. Today we are using `rem` for layout but `pixels` for font-sizes. 

Give it a go, let me know if you need any assistance.

**Comment by maxshearer** [comment]
Should be pretty straightforward. Famous last words. If I get time I'll try and do it this evening.

**Comment by marcustisater** [comment]
hehe, that's ambitious. Good luck... :smiley: 

I will be available tonight if you have any questions.
