### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by okonet** [postcss/postcss.org#177]
I've accidentally pushed to master. Although it was my fault, I think we should not allow that and enforce PRs by protecting the master branch: https://help.github.com/articles/configuring-protected-branches/

**Comment by mxstbr** [comment]
It is protected, but admins can still push, so we don't have to go through a PR with LGTM for a simple typo fix etc.

**Comment by okonet** [comment]
Makes sense

Sincerely yours

Andrey Okonetchnikov

@okonetchnikov
http://okonet.ru

**Comment by marcustisater** [comment]
Yeah that's correct, you have write access. We trust you :wink:

**Comment by marcustisater** [comment]
I f**** up some merge conflicts so I'm going to rollback to a4112ea

@okonet is it cool if you redo the pull request again?

**Comment by marcustisater** [comment]
nvm, let me fix this. It's my mess. It should be resolved any minute
