### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#19]
There should be some very good documentation of PostCSS on the website. Here are some quick initial ideas;

* How to get started
* Developer API
* PostCSS in a nutshell 

etc...

There are already some very good documentation on the PostCSS GitHub page that we can use.

**Comment by MoOx** [comment]
And probably some good idea http://webdesign.tutsplus.com/series/postcss-deep-dive--cms-889

**Comment by ai** [comment]
We have a special section in README.md right now with most important docs:
https://github.com/postcss/postcss#articles

**Comment by marcustisater** [comment]
If someone is contributing with documentation they have to agree by [Creative Commons Legal Code](https://creativecommons.org/licenses/by/3.0/legalcode). This is something we need to have in the repository listed.

**Comment by ai** [comment]
BTW, why we use here CCPL 3.0, and not CC-BY-4.0?

**Comment by marcustisater** [comment]
Ok, CC-BY-4.0 is fine by me. Is that what you are using on [PostCSS](https://github.com/postcss/postcss) repo?

**Comment by ai** [comment]
Nope, we use MIT in PostCSS. We use CC-BY in PostCSS Brand repo.

**Comment by marcustisater** [comment]
Ok, let's go with CC-BY-4.0, let me set it up.

**Comment by marcustisater** [comment]
Once we have established a nice sitemap for the documentation part, I can start creating issues that would need "content/documentation". Maybe we should use the GitHub wiki? 

#48

**Comment by mxstbr** [comment]
@marcustisater if we have the documentation in Markdown files in the repo, we can generate the website from that. If it's in the wiki, that isn't possible.

**Comment by marcustisater** [comment]
Yeah that's a good point but I'd figured maybe the GitHub Wiki can be easier to contribute with and maybe we can add some overview planning on what's done and what's not in the wiki as well. 

Do you think it's worth investigating into more if it's worth adding it in? I haven't used it at all to be honest...

**Comment by mxstbr** [comment]
A wiki is nicer for collaboration, but we'd essentially have to copy & paste every change which is a pita. I don't think it's worth investigating tbh, there's a lot of documentation at postcss/postcss in Markdown already: https://github.com/postcss/postcss/tree/master/docs

**Comment by marcustisater** [comment]
Yeah, you're right. I didn't think about that part... :blush:

**Comment by MoOx** [comment]
That's a reason why I included cssnext website in cssnext repo itself: to avoid redundancy and make maintenance easier. And I am pretty happy with this choice.

**Comment by marcustisater** [comment]
All that we need is a good README file that explains how to contribute with content for the website.

**Comment by marcustisater** [comment]
I can set one up.

**Comment by marcustisater** [comment]
Feel free to edit if needed.

#73

**Comment by marcustisater** [comment]
breaking this down into more issues, my fault.
