### ISSUE TITLE
Update Statinamic 0.8.2

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#190]
https://github.com/MoOx/statinamic

**Comment by thangngoc89** [comment]
Update 0.7.0 to 0.8.0: https://github.com/thangngoc89/blog/commit/33b95be45da5b3265fc09cc4c7f523ca3d533e05

**Comment by marcustisater** [comment]
@thangngoc89 - do you think it's a good idea to [wait](https://github.com/postcss/postcss.org/issues/167) for 9.0, how far are you guys from that or is version 8.0 cricual?

**Comment by thangngoc89** [comment]
0.9 will be release soon. I think you guys should wait for it.

**Comment by thangngoc89** [comment]
@marcustisater forgot to mention, 0.8.2 has appcache support out-of-box. Should be great a document website like postcss

**Comment by marcustisater** [comment]
Updated to 0.8.0, I will wait for 0.9.0 release.
