### ISSUE TITLE
Thank you all

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#191]
Hello everyone,

[Milestone 1.0](https://github.com/postcss/postcss.org/milestones/1.0) has come to an end :tada:  I would like to take the time to really thank ya’ll for the time you have put into the making of postcss.org first release. It’s incredible to see so many people being passionate about open source and contributing time and effort into this.

With that being said - I’m looking forward to "announce" [Milestone 1.1](https://github.com/postcss/postcss.org/milestones/1.1) - main focus will be on building up basic pages and the official plugin search/page. I’m still doing some reorganizing to really make it straight forward.

On top of that I also wrote my very first [blog post](http://marcustisater.se/postcss-to-goal/) about the making of [postcss.org](http://www.postcss.org) - I appreciate if you take 5-10 minute to read it.

Thank you once again everyone :heart: 

@ai @okonet @MoOx @mxstbr @jeddy3 @thangngoc89 @halvves @stephenway @hudochenkov @maxshearer

**Comment by ai** [comment]
@marcustisater thanks you too. It was really awesome example of good open source management. You are Oppenheimer of postcss.org :).

**Comment by marcustisater** [comment]
haha, thank you! :joy: 

I'm really looking forward for the future and making room to get the next few release going.

**Comment by MoOx** [comment]
Nice post! Thanks for sharing this experience 👌

**Comment by jeddy3** [comment]
Excellent blog post! Well done :)

A couple of minor suggestions:

1. Typo in "Linting with Stylint & ESLint" -> "stylint" is a stylus linter. I think you meant "stylelint".
2. Perhaps there's an opportunity to mention that both CSS Modules and stylelint are powered by PostCSS (for parity with the website itself) e.g. "For our styles, we chose Stylelint and configured stylint-config-standard." becomes "For our styles, we used the PostCSS-powered Stylelint and configured using the stylint-config-standard shareable config.". Perhaps you can work something similar into your CSS Modules description.

And as ai said, thanks so much for steering the postcss.org! We built stylelint.io off the back v1 of postcss.org, and so a big thanks for everyone's hard work on it :)

**Comment by marcustisater** [comment]
Thanks :smile: 

Whoops, nice catch @jeddy3. I will definitely fix that typo and embrace that CSS Modules and Stylelint is powered by PostCSS. Thanks for the feedback.
