### ISSUE TITLE
SEO optimized PostCSS home page content

### ISSUE THREAD

**Issue by okonet** [postcss/postcss.org#199]
For some reason I'm seeing an Autoprefixer description here.

<img width="521" alt="2016-03-15 at 10 23" src="https://cloud.githubusercontent.com/assets/11071/13773137/1848b30e-ea98-11e5-8c6d-810e7bdf53cb.png">

This also applies to search results: https://duckduckgo.com/?q=postcss&ia=about

It seems to happen since it's the first meaningful content on the page. I think we should add a bit longer explanation to the page between examples and the header. This should serve 2 purposes: fixes SEO issues and also explain a bit more what PostCSS is.

**Comment by maxshearer** [comment]
Missing both `<meta name="description" content="...">` and `<meta property="og:description" content="...">` which should do the trick.

And on that note, if we're doing that we might as well add the [Twitter OG](https://dev.twitter.com/cards/markup) tags in too.

**Comment by marcustisater** [comment]
`{ property: "og:description", content: head.description }` should do the trick. I can submit PR.

**Comment by awayken** [comment]
Is anyone working on this? I decided to give it a look, since it looked like an easy enough PR to submit. The `content/index.md` file is missing copy for a description field, so I took a shot at writing something for it:

> Transform CSS with the power of JavaScript. Auto-prefixing, future CSS syntaxes, modules, linting and more are possible with over hundreds of PostCSS plugins.

Thoughts? It's short to adhere to the 160 character rule for meta descriptions, but it still references most of the homepage copy.

**Comment by thangngoc89** [comment]
@awayken I'm not familiar enough to PostCSS to have comment about the description. But if you did a PR for this. Remember to uncomment these lines

https://github.com/postcss/postcss.org/blob/b1af8cf1e4d1838d61c837eaf59a8fb3a679e91f/web_modules/layouts/HomePage/index.js#L42

`twitter:description`

and normal `description` too.

**Comment by awayken** [comment]
@thangngoc89 I think I'm good there. I took out the comments and added `{ name: "description", content: head.description },` for the normal description. The HTML showed up but the content was blank. That lead me down into the content folder, where I noticed there was no description to output.

**Comment by marcustisater** [comment]
Description text looks good, submit a PR and we can review it from there. 

Have a look at https://github.com/postcss/postcss.org/blob/master/web_modules/layouts/Page/index.js that's the most recent one I updated with description meta tags.
