### ISSUE TITLE
Enable appcache for offline access

### ISSUE THREAD

**Issue by thangngoc89** [postcss/postcss.org#200]
Since the content of this website is rarely changed, it would be a great user experience to enable it. [It's just 1 line away](http://moox.io/statinamic/docs/advanced/offline-browsing/)

**Comment by ai** [comment]
This feature will be extremely useful when we will have API page.

**Comment by thangngoc89** [comment]
I can send a PR for this if you like

**Comment by marcustisater** [comment]
I agree, you are good to go for a PR.

Is it possible to integrate Service Worker, how is support looking for Statinamic?

**Comment by thangngoc89** [comment]
For service worker, see https://github.com/MoOx/statinamic/issues/153

PRs are welcome by the way. I and @-MoOx just don't have enough time to implemented it

**Comment by marcustisater** [comment]
Yeah, it's a big implementation. I think appcache is fine for this website :smile:

**Comment by thangngoc89** [comment]
IMHO, the deadline is when Firefox deprecated this feature. There are warnings in console now.

**Comment by marcustisater** [comment]
Oh, I didn't know that, I totally agree with you.

**Comment by mxstbr** [comment]
Will do

**Comment by marcustisater** [comment]
Thanks for quick PR @mxstbr
