### ISSUE TITLE
Add Wikipedia logo to Trusted by industry leaders section

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#207]
Wikipedia CSS processing is based on PostCSS-only solution. So we should definitely add Wikipedia as PostCSS user. Maybe instead of Google (because Google not uses PostCSS-only solution).

**Comment by ai** [comment]
@marcustisater I already updates users list in README.md https://github.com/postcss/postcss/commit/382da0ef48c569fff1876582ceace820f0633ddb

**Comment by marcustisater** [comment]
Alright, I can update it. Do you have the official logo in `.svg` format?

**Comment by okonet** [comment]
I could take care of it. I would not remove google though

**Comment by marcustisater** [comment]
I agree, try add it on the same row or split it as 3 column grid.
