### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#21]
@ai mentioned an idea to create a migration guide for PostCSS

**Comment by ai** [comment]
Maybe we can merge with idea with that wizard. Just ask first question: “Is it a new project or legacy one”

**Comment by marcustisater** [comment]
Yeah, would be cool. We could start with some initial documentation combined with #19

**Comment by GrosSacASac** [comment]
might as well close this issue in 2022
