### ISSUE TITLE
Add Facebook logo

### ISSUE THREAD

**Issue by okonet** [postcss/postcss.org#212]
Since Facebook now officially uses PostCSS (https://code.facebook.com/posts/879890885467584), we should add a logo to the home page.

@kangax confirms we can: https://twitter.com/kangax/status/742472607732273152

**Comment by marcustisater** [comment]
Absolutely, that's awesome.

PR Welcome.

**Comment by marcustisater** [comment]
Can you attach the official logo in svg format?

**Comment by okonet** [comment]
Forgot to create a branch but it should be fixed by f94b19e

**Comment by marcustisater** [comment]
No worries.

Looks good.

**Comment by mxstbr** [comment]
We could link to their article when clicking on the logo?

**Comment by marcustisater** [comment]
Sure, why not. When we eventually get a [basic page](https://github.com/postcss/postcss.org/issues/119) layout up, I figured we could have a page for [articles](https://github.com/postcss/postcss.org/issues/84) too. 

Up for a quick PR @mxstbr? ;)

**Comment by ai** [comment]
I suggest to replace Google. Also we could add GitHub logo as well.

**Comment by okonet** [comment]
Why remove Google?

Can you add an issue for Github?

**Comment by ai** [comment]
@okonet because we know only about some small side project.

**Comment by marcustisater** [comment]
I can open a new issue for this discussion. I personally think all the logos should stay and we can break them into several rows. When we get basic pages, we can have a page that says "Companies using PostCSS" and then just feature a few on the front page instead.

**Comment by marcustisater** [comment]
#214
