### ISSUE TITLE
Add GitHub logo

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#214]
GitHub [uses Stylelint](https://github.com/stylelint/stylelint/issues/1402#issuecomment-225282315) and Autoprefixer, so we can add them to Users

**Comment by marcustisater** [comment]
Sounds good, which logotype should we use? Maybe just the icon itself? Attach svg.

**Comment by ai** [comment]
https://github.com/logos

**Comment by ai** [comment]
I think we could use mark and logotype together

**Comment by marcustisater** [comment]
Is that officially "allowed" to do? Otherwise, Yes I agree.

**Comment by marcustisater** [comment]
It says _"Create a modified version of the Octocat or GitHub logo"_, but it's not really modifying, is it?

**Comment by okonet** [comment]
It is. I'd go with the type version since it's most explicit one

**Comment by okonet** [comment]
And it's a "logo" — the other too are just some signs that are connected with GitHub.

**Comment by marcustisater** [comment]
Thanks for clarifying that. Let's go with the type version.
