### ISSUE TITLE
OpenGraph issue

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#218]
Facebbok reports `Object at URL 'http://postcss.org/' of type 'article' is invalid because the given value '/' for property 'og:url' could not be parsed as type 'url'.`

**Comment by thangngoc89** [comment]
We fixed this a while ago. 

https://github.com/MoOx/phenomic/issues/104

**Comment by thangngoc89** [comment]
You'll will need to update this line 

https://github.com/postcss/postcss.org/blob/master/web_modules/layouts/HomePage/index.js#L41

with 

https://github.com/MoOx/phenomic/blob/cd1afa414e5db6ccb0e82797e4ee287943e169a6/docs/web_modules/layouts/Page/index.js#L50

Aslo, replace it in others layout

**Comment by marcustisater** [comment]
I can update it. Thanks @thangngoc89
