### ISSUE TITLE
Lost in examples

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#219]
Should we add Lost grid to PostCSS plugins examples? It is popular. It has nice logo. Also 5 plugins is still small number (we should keep this list short).

@marcustisater @peterramsing what do you think?

**Comment by peterramsing** [comment]
@ai I think it would be awesome! 👍 

Here is the logo if you need it: 
![lost-icon](https://cloud.githubusercontent.com/assets/3523268/17829114/9db007ae-6658-11e6-9ed7-a5e929a6eb0c.png)

**Comment by ai** [comment]
What input/output example we can show?

**Comment by marcustisater** [comment]
Great idea, I'm still on vacation but I will be back next week to do a bit more work on the website.

**Comment by marcustisater** [comment]
> What input/output example we can show? 

https://github.com/peterramsing/lost#getting-started, maybe?

**Comment by peterramsing** [comment]
I'll see if I can do a PR in the next few days. I dove in and had some trouble getting it to build so I tabled it for the moment but will see if I can get some more time tonight. So much other work to do. 😳

**Comment by marcustisater** [comment]
Shoot, just message me on gitter if you need any help to get the build up and running. You can log me the errors.

**Comment by halvves** [comment]
@marcustisater @peterramsing Being a big lost fan myself (used in my last couple of projects work), I'd love to make a quick PR to add this. Just want to be sure no one else has embarked on this before I do.

**Comment by marcustisater** [comment]
Go a head, I have a lot of work so I haven't really had the time unfortunately

**Comment by peterramsing** [comment]
Sorry–I totally spaced on this. Thanks @halvves!

**Comment by peterramsing** [comment]
Also, we're working hard to keep improving out site if you want to link there: http://lostgrid.org/

Thanks again and let me know if you need anything!

**Comment by marcustisater** [comment]
Made a quick PR. Let me know if you want any changes @peterramsing 

<img width="815" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2952332/21744554/49c38074-d518-11e6-96a4-6db2c4b8498f.png">

**Comment by peterramsing** [comment]
@marcustisater That looks perfect! ...thanks for doing that!

**Comment by marcustisater** [comment]
No worries man!
