### ISSUE TITLE
Add Gitter button

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#224]
Gitter has a embedded chats. We should add it to `postcss.org`!

https://sidecar.gitter.im/

**Comment by marcustisater** [comment]
Good suggestion.

I can't make any promises but I will try to have a look after new years when I'm off work. Sorry @ai for lacking with the updates

**Comment by ai** [comment]
@marcustisater don’t worry, I created a issue on Cult of Martians to bring new opensource contributers. I think it is good task for first PR.

**Comment by marcustisater** [comment]
Awesome, but you see... there is a problem with the Phenomic build #223 😕

**Comment by ai** [comment]
We could not use old Phenomic, which worked well?

**Comment by marcustisater** [comment]
The script broke, unknown reason. https://github.com/postcss/postcss.org/issues/220

**Comment by marcustisater** [comment]
I know @halvves was working on it but I haven't really checked status, will try to do this weekend.

**Comment by ai** [comment]
@marcustisater script is fixed and I could send people to fix this issue?

**Comment by marcustisater** [comment]
Yeah, the build seems to be running. Let me try add the gitter button tonight and I will double check that everything is working as expected. I will text you on gitter tonight, ok?
