### ISSUE TITLE
Are these typos on the landing page?

### ISSUE THREAD

**Issue by aymericbouzy** [postcss/postcss.org#236]
I see two things that look like typos to me, but I'm only a beginner, so pardon my ignorance if I'm wrong.

On http://postcss.org/

1. `:fullscreen` becomes `:full-screen` : is the `-` intended? It worries me that PostCSS is going to insert an hyphen.
2. `lost-column: 1/3` without the `;` : are semi-column not required anymore? is that future CSS? Why put semi-columns everywhere else then?

If these aren't typos, maybe consider adding a note about why on the landing page, otherwise it's confusing. Or having more straightforward examples (either putting semi-columns everywhere or nowhere for instance).

**Comment by azat-io** [comment]
1. It's ok. Look [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen)
2. You do not need semicolon if your selector has only one CSS rule
