### ISSUE TITLE
travis build fail

### ISSUE THREAD

**Issue by lcxfs1991** [postcss/postcss.org#237]
![image](https://user-images.githubusercontent.com/3348398/35106456-3874353e-fca9-11e7-87a6-4e62d25ed457.png)

**Comment by marcustisater** [comment]
Sorry, we haven't had this website update for a while. What node version are you running?

**Comment by lcxfs1991** [comment]
I run successfully on my MAC. It is node 8. However, it fails on travis machine. It is node 5 which is defined by `.travis.yml`.

**Comment by lcxfs1991** [comment]
any updates here?

**Comment by lcxfs1991** [comment]
I think the site is deployed after travis-ci is buited successfully.
I am trying to translate it into Chinese and find this issue. i just make a pr.

https://github.com/postcss/postcss.org/pull/238

**Comment by thangngoc89** [comment]
@lcxfs1991 This site needs a refactor. I'm a maintainer of Phenomic (the framework that's used to power this site). Phenomic has changed a lot since the last commit. And I think it's better to implement a proper i18n solution to the site

**Comment by lcxfs1991** [comment]
Thanks! Do you have a schedule for this?

**Comment by marcustisater** [comment]
Travis is running on node 8 now. Thanks for PR.

@thangngoc89 hope you are doing well. I have been busy with work lately, if you have time to refactor the codebase to be up-to-date with Phenomic that would be awesome.

**Comment by marcustisater** [comment]
closed due to inactive. 

I still got problems with Travis tho, created new issue for that.

to answer @lcxfs1991 question, no sorry we do not.
