### ISSUE TITLE
[CSS Parser] @import's url and media parameter aren't being separated

### ISSUE THREAD

**Issue by ianthedev** [postcss/postcss.org#249]
Currently, parsing the text of this style sheet:

```HTML
<style>
    @import url('landscape.css') screen and (orientation: landscape);
</style>
```

is getting this result:

```
{
    "type": "root",
    "nodes": [
        {
            "type": "atrule",
            "name": "import",
            "params": "url('landscape.css') screen and (orientation: landscape)"
        }
    ]
}
```

The `@import` at-rule's url and media parameter aren't being separated in the parsed result. Is that working as intended?

**Comment by ai** [comment]
Yeap. Because at-rule params syntax could be very different (especially in plugins with custom syntax and unknown at-rules).
