### ISSUE TITLE
Request for Clearer Gitter Room Descriptions

### ISSUE THREAD

**Issue by wesleyboar** [postcss/postcss.org#251]
For a new user looking for support from Gitter, they are presented with [the PostCSS Gitter home page](https://gitter.im/postcss/home) that shows:

| All Rooms | | |
| :- | :- | :-: |
| postcss | Transforming CSS with JS plugins | `JavaScript` `Framework` `CSS` |
| postcss.org | | |

Yes, likely the user can figure out which room to enter, but not all users do. There are some users coming to the `postcss.org` room, and asking `postcss` questions. I suggest using the descriptions to clarify the rooms' purpose, and a tag (if available) for the `postcss.org` room.

New descriptions will not reduce all misdirected traffic, but it reduces _some_, and having them would be more professional and clear, with (assumption warning) minimal effort. Example descriptions:

| All Rooms | | |
| :- | :- | :-: |
| postcss | Learn how to transform CSS with JS plugins | `JavaScript` `Framework` `CSS` |
| postcss.org | Discussion for PostCSS.org Website only | `Website` |

**Comment by ai** [comment]
Done. Thanks for the useful idea.
