### ISSUE TITLE
Content Strategy

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss.org#26]
### Refine and clarify your goals

Determine what you want to accomplish.

1. Communicate differentiation
1. Provide overview of quote process
1. Show value through rich media
1. Outline next steps *(testimonials, referrals, etc.)*

Define who will be visiting your website and what you want them to do. Primary and secondary audiences should be considered on every page.

## Demographics
Example of basic traits of people that fit into your audience.

* Age (25-34 & 45-54)
* Location
* Gender (Female & Male)
* Income
* Education
* Occupation
* Ethnicity
* Marital Status
* Number of Children

## Psychographics
Based on the demographic, this helps you talk to your audience.

* Personality
* Attitudes
* Values
* Interests/hobbies
* Lifestyle
* Behavior

## Resources

You can start your research with these tools:

* [US Census Bureau >](http://www.census.gov/)
* [Google Analytics >](http://google.com/analytics/)
* [Facebook Insights >](https://www.facebook.com/insights/)

**Comment by marcustisater** [comment]
Let me know if you need help planning this one out, it's probably going to be more one of the more difficult ones to create a good strategy.

**Comment by stephenway** [comment]
Basic questions added, I'll have more time tonight to start filling in the blanks, anyone can help answer as well :smile:

**Comment by marcustisater** [comment]
We need a README file for how to contribute with content.
