### ISSUE TITLE
Move to Vite

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#266]
Vite `node_modules` footprint is smaller and performance is better.

**Comment by TheSeally** [comment]
@ai I I started migrating to vite, but found problem.
For now postcs.org inline all styles into html. Vite inline styles only in serve mode. When I build project it inject style via link tag.

Is inline style used to optimize loading? Or we can inject styles via link tag? 

Anyway, I continue to explore the possibility of inlining styles

**Comment by ai** [comment]
Yeap, it is an optimization, but we can avoid it

**Comment by sult4novars** [comment]
@ai hi! I have created pr for this issue. Please review it https://github.com/postcss/postcss.org/pull/270
