### ISSUE TITLE
Open Source Design

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss.org#27]
[Invision](https://invisionapp.com) - Emailed Support about OSS Plans
[Zeplin](http://zeplin.io) - Offering free plan with 3 projects
[Pixelapse](https://www.pixelapse.com) - Unlimited public projects! Thanks @patrick91 

@marcustisater - Need issue labels for `design` and `design needed`.

**Comment by patrick91** [comment]
This [article](http://una.im/open-source-design/#💁) by @una could be helpful :)

**Comment by marcustisater** [comment]
Reminder to check with support if invasionapp or similar can offer free plans for PostCSS.com

**Comment by marcustisater** [comment]
There you go, I think you should have access to make changes to labels as well.

**Comment by marcustisater** [comment]
Suggestion from @stephenway to go http://www.pixate.com/ instead?

**Comment by mxstbr** [comment]
Suggestion: https://marvelapp.com/

**Comment by stephenway** [comment]
Sorry @marcustisater I mis-remembered the name of pixelapse on our chat, pixate is entirely different.

**Comment by marcustisater** [comment]
Yeah figured, meant to say Pixelapse?

**Comment by stephenway** [comment]
In an effort to keep us all in the same ecosystem with minimal setup, I've identified a workflow that we can easily setup to keep using Github for our design. I have updated the brand repo with this workflow to show how we can leverage SketchTool to export slices into the repo for each commit. This provides us with diffing per commit, and hosting for free.

**Comment by stephenway** [comment]
We can use Zeplin for handoff once we have have an approved layout.

**Comment by marcustisater** [comment]
We need still need to add the boilerplate to the repository and also include well documented REAME files of how the process will go. I can help you.

**Comment by marcustisater** [comment]
cc @okonet
