### ISSUE TITLE
Website visual change proposals

### ISSUE THREAD

**Issue by imchell** [postcss/postcss.org#275]
## What’s the problem
* Font weight of side menu is too heavy, which always attracts users’ attention to side menu instead of doc right in the center of the page.
* Table lacks of contrast when it compares to other content of the doc.
* Many different font sizes lead to distraction (`navlink`, `sidemenu_section`, `sidemenu_child`, `doc_title`, `doc`, `doc_subtitle` all have different sizes).
* Inconsistency between homepage & API page. The navigation bar of the API page sticks to the top when scrolling down while homepage doesn’t.

## Possible Solutions
* Reduce side menu font weight.
* Polish the style of table.
* Use color & font weight to indicate hierarchy instead of font sizes.
* Stick navigation bar to the top always.

### API Page Before
![API Page Before](https://github.com/imchell/pics-and-files/blob/master/postcss/API%20Before.png?raw=true)
### API Page After
![API Page After](https://github.com/imchell/pics-and-files/blob/master/postcss/API%20After.png?raw=true)
### Homepage Before
![Homepage Before](https://github.com/imchell/pics-and-files/blob/master/postcss/Home%20Before.png?raw=true)
### Homepage After
![Homepage After](https://github.com/imchell/pics-and-files/blob/master/postcss/Home%20After.png?raw=true)

---
These are just my personal opinion. Don't know whether it is good enough to tweak the design.

**Comment by ai** [comment]
I like the changes.

A question:
1. What sidemenu links will be highlighted in red like `Comment` in your example?

A few changes:
1. No transparent background since it reduce readability
2. Can we make table header in API less aggressive? Users should look at table content, not table header.

**Comment by imchell** [comment]
> 1. What sidemenu links will be highlighted in red like `Comment` in your example?

When the section is expanded.

> 1. No transparent background since it reduce readability

Yes pure color would be better. I noticed that mobile size has adopted pure color.

> 2\. Can we make table header in API less aggressive? Users should look at table content, not table header.

I will try to use a light blue seperation line instead.

**Comment by ai** [comment]
> When the section is expanded.

Let’s try 👍

> I will try to use a light blue seperation line instead.

We can try. Show how it will look like.
