### ISSUE TITLE
Update to new PostCSS

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#284]
In [recent PostCSS version](https://github.com/postcss/postcss/pull/1815) we broke API generation

**Comment by freydev** [comment]
https://github.com/postcss/postcss.org/pull/285

Поправил генератор, починил парсер разделов которые были пустые на проде.
не понял почему разделы `['LazyResult', 'Processor', 'Container', 'Node'] ` были заигнорены, ведь они есть на проде, на всякий случай включил и не понял почему игнорится ChildProps, теоретически для него можно написать отдельный сценарий.
