### ISSUE TITLE
Docs links lead to 404

### ISSUE THREAD

**Issue by scrhartley** [postcss/postcss.org#295]
Using main nav bar, [Docs](https://postcss.org/docs/) and [Plugins](https://postcss.org/docs/postcss-plugins) links show 404 page.

![image](https://github.com/user-attachments/assets/5e265daf-e9dd-4f91-bfd2-b4f5ff45f295)

**Comment by ai** [comment]
Thanks. Fixed https://github.com/postcss/postcss.org/commit/cddfb7e018747d065f5a62df6aa01e07368fbd43
