### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#3]
Andrey mentioned in [ticket 391](https://github.com/postcss/postcss/issues/391) that he is looking for some really nice artwork for this website, something that PostCSS seems to have quite frequently on Twitter, posts etc...

> Also I want a good art work for site. Something like pixelart or/and watercolor. Funny but about black magic. Can you recommend a good artists to place a order?

**Comment by MadLittleMods** [comment]
> [Here is a list of artists](https://gist.github.com/MadLittleMods/e0fa5ed14def5fea1a65) I gathered so far.
> https://github.com/postcss/postcss/issues/391#issuecomment-115523251

**Comment by ai** [comment]
I also wrote to one Russian designer, who wrote me by email.
