### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by mxstbr** [postcss/postcss.org#48]
Before we begin actually designing and building the website, we need a coarse overview of the modules/pages the website needs for `v1`. This is what I imagine currently:

```
postcss.com
├── Documentation
├── AST Explorer    <-- Is this v1?
├── Plugins         <-- (List, wizard is v1.1)
└── Get involved
```

**Comment by marcustisater** [comment]
This goes along with #26 - to create more issues, great point bringing this up. I've been meaning to do so myself.

I can sketch up a quick **sitemap** with my thoughts.

**Comment by marcustisater** [comment]
I will have one ready for Thursday - caught up with work :cry:

**Comment by marcustisater** [comment]
This is my very first thoughts about the sitemap structure, need some help and feedback.

![first-draft](https://cloud.githubusercontent.com/assets/2952332/12335871/adf62e7a-bb01-11e5-8f47-8224c89fbfa9.png)

I have this setup on mindmeister. Here is a public url to help contribute to it. https://mm.tt/632990172?t=C2Qo6uvzTk

**Comment by marcustisater** [comment]
If we really can get together an completed sitemap it can be easier to split up issues for content that we need.

**Comment by mxstbr** [comment]
Is this launch only?

**Comment by marcustisater** [comment]
Sorry? This sitemap needs improvement, it should be ready before launch, yes.

**Comment by mxstbr** [comment]
I meant, should we only add pages that have to be ready for launch? Otherwise the Wizard thing is missing under Plugins.

**Comment by marcustisater** [comment]
I gotcha, sorry.

Yes, launch only.

**Comment by marcustisater** [comment]
cc @ai, @stephenway, @MoOx would love you're feedback and help on this one - others are welcome to edit this sitemap as well of course :smile:

**Comment by ai** [comment]
I think `Writing a Plugin` should be docs. Because we have also custom plugins, which will not be part of Plugin catalog.

**Comment by ai** [comment]
We need a API in Documentation or Learn. Because this API is useful not only for plugin developers, but also for runner developers (like `gulp-postcss`) or non-plugin tools like CSS concat.

**Comment by stephenway** [comment]
I could see adding a page to formalize the process of submitting plugins, or for that matter every page has a link to the equivalent content file on github so they can edit it there and create a pull request.

**Comment by marcustisater** [comment]
Thanks for quick feedback, will update into a more full version to discuss over.

**Comment by marcustisater** [comment]
quick update

<img width="811" alt="sitemap-2" src="https://cloud.githubusercontent.com/assets/2952332/12367281/1dce75b0-bbe1-11e5-9643-f0ecac530da3.png">

**Comment by ai** [comment]
@marcustisater looks good

**Comment by marcustisater** [comment]
Thanks, I guess this would be a quick start to create issues from what content we need on the website. I will leave this issue open.

Feel free to add more pages or modifications if wanted.

**Comment by marcustisater** [comment]
updated again

![sitemap-3](https://cloud.githubusercontent.com/assets/2952332/12374542/b53b4ba4-bc9e-11e5-8852-db1d6afedec6.png)

**Comment by marcustisater** [comment]
I broke this issue into #83
