### ISSUE TITLE
Domain for (.io, .org) 

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#49]
@ai can you hook me up with the .io and .org domain on gandi so I can set it up

**Comment by MoOx** [comment]
Btw, .com is weird (means .commercial right?)
.org make more sense.
.io is more geek.

**Comment by ai** [comment]
`.io` domain is not on Gandi. It is on Russian webnames.ru

Do we need this domain, because its registration date will end soon?

**Comment by ai** [comment]
@marcustisater I add you to `.org`

**Comment by marcustisater** [comment]
Yeah, `.com` stands for commercial. Let's do redirect to .org, I like it as well. What do you think @ai ?

Hmm, how much does it cost to renew it? Do we need `.io`?

**Comment by marcustisater** [comment]
It's always nice to "eliminate" as many domain as possible for postcss so nobody else can steal it :wink:

**Comment by azat-io** [comment]
```.io``` better than ```.org```

**Comment by mxstbr** [comment]
> .io better than .org

Why?

**Comment by ai** [comment]
`.io` is worse, because it has wrong semantic. It is British Indian Ocean Territory. It is just a short-term trend.

**Comment by marcustisater** [comment]
domain is now set to .org instead of .com awaiting approval for https://github.com/postcss/postcss.org/pull/54

**Comment by mxstbr** [comment]
Already merged. :+1:
