### ISSUE TITLE
Rename project to .org?

### ISSUE THREAD

**Issue by ai** [postcss/postcss.org#50]
I thought that we all decided to use `postcss.org`, because it is not *com*mertial project (unfortunately) and we are not members of [British Indian Ocean Territory](https://en.wikipedia.org/wiki/.io). So, maybe we need to rename repo?

**Comment by mxstbr** [comment]
:+1:

**Comment by marcustisater** [comment]
Indeed, I can fix that.

**Comment by marcustisater** [comment]
Domain is fixed.
