### ISSUE TITLE
Use postcss-cssnext in the boilerplate?

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss.org#53]
This is a quick follow-on to @MoOx's [comment](https://github.com/postcss/postcss.com/issues/13#issuecomment-169463835) in the boilerplate issue and the [`stylelint` PR](https://github.com/postcss/postcss.com/pull/52).

Are you be willing to accept a PR that replaces the [current](https://github.com/postcss/postcss.com/blob/master/package.json#L41) individual postcss plugins, of `postcss-custom-media` and `postcss-custom-properties`, with the `postcss-cssnext` plugin pack? I'll then be able to use its [nesting feature](http://cssnext.io/features/#nesting) as a replacement for @MoOx's use of indentation that I had to nuke in https://github.com/jeddy3/postcss.com/commit/592fe836fd6fa04f042b5fa064f6a07d5daa7787#diff-8a4b7dda92b463014bdba201b85229b6R24.

I figured it would be better to include `postcss-cssnext`, rather than request the addition of just `postcss-nesting`, as `postcss-cssnext` seems to be—like `stylelint`—featured in the early design mock-ups.

There are a few rules—[`function-calc-no-unspaced-operator`](https://github.com/stylelint/stylelint/blob/master/src/rules/function-calc-no-unspaced-operator/README.md), [`media-feature-range-operator-space-after`](https://github.com/stylelint/stylelint/blob/master/src/rules/media-feature-range-operator-space-after), [`selector-pseudo-element-colon-notation`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-pseudo-element-colon-notation/README.md) etc—within `stylelint-config-standard` that are geared towards the features of `postcss-cssnext`, and so I think they will be an excellent fit for each other.

What do you think?

**Comment by mxstbr** [comment]
Yes, I'd love that! I haven't done anything with the config yet, but we should really showcase what PostCSS is capable of with this website! Please submit a PR!

**Comment by MoOx** [comment]
Should do the same in the default boilerplate for cssnext and stylelint.

**Comment by jeddy3** [comment]
> Should do the same in the default boilerplate for cssnext and stylelint.

Sounds like a plan :)

**Comment by marcustisater** [comment]
Yup, I agree as well. Great pointers @jeddy3
