### ISSUE TITLE
[Landing Page] Plugins

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#56]
From the sitemap ( #48 ) - we have decide that there is going to be a page of PostCSS Plugins to pick from. I am thinking that the landing page would include the Plugin Search( #17 ) and then there would be a list similar as a sidebar navigation menu to group PostCSS plugins as a categories. 

**What do we need?**
1. Landing page mockup of how the plugins page would look like including the search as well how the user can navigate to find more plugins to choose from. 
2. Mockup for individual PostCSS categories pages
3. Mockup for individual PostCSS plugin pages when clicked or hyperlink for GitHub/NPM?

**Comment by marcustisater** [comment]
@stephenway when you have figured out the #27 - we can get this issue started with PRs open.

**Comment by ai** [comment]
@mxstbr it good with making a plugin catalog.

But we need make it automatically with npmseach.com

**Comment by ai** [comment]
Also let’s promote plugins pack in search. We can force them to use some specail keyword in `package.json`.
