### ISSUE TITLE
[Landing Page] Blog

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#57]
We have discussed creating a "Blog" section for the website including a Twitter feed of some kind having users to look up the latest news about PostCSS and it's community.

![skarmavbild 2016-01-16 kl 12 02 36](https://cloud.githubusercontent.com/assets/2952332/12372038/1085835e-bc49-11e5-83c7-283d0ded6972.png)

**Comment by marcustisater** [comment]
![skarmavbild 2016-01-16 kl 12 02 36](https://cloud.githubusercontent.com/assets/2952332/12372038/1085835e-bc49-11e5-83c7-283d0ded6972.png)

**Comment by marcustisater** [comment]
What do you guys think of this? My biggest fear is that this wouldn't get very updated and become a very "dead part" of the website :fearful:

**Comment by mxstbr** [comment]
I agree, I don't think it's necessary, but maybe we could post releases and stuff there. What do you think @ai?

**Comment by marcustisater** [comment]
Yeah, maybe more of a CHANGELOG approach instead?
