### ISSUE TITLE
[Page/Section] FAQ

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#58]
We need some content and suggestions for the FAQ(Frequently Asked Questions) section.

Example: 

**Can I still use Sass?**
_Yes, you can still compile....etc_

**Where can I find the API documentation?**
_You can find it at ....._

Please read through our [contributing guidelines](https://github.com/postcss/postcss.org/blob/master/docs/content.md) before you start.

https://github.com/postcss/postcss.org/blob/master/content/learn/introduction/faq.md

**Comment by marcustisater** [comment]
Please read through our contributing guidelines(https://github.com/postcss/postcss.org/blob/master/docs/content.md) before.

Start writing suggestions here - https://github.com/postcss/postcss.org/blob/master/content/learn/introduction/faq.md

**Comment by ben-eb** [comment]
**Q:** *Why doesn't PostCSS support single line comments?*
**A:** Single line comments are not a language feature of CSS, so PostCSS does not parse them by default. Instead, load [postcss-scss](https://github.com/postcss/postcss-scss) as a custom parser to enable this support.

**Comment by marcustisater** [comment]
Thanks Ben,

We will have to talk over the strategy of documentation pages for the website, maybe we can sync the [PostCSS repo](https://github.com/postcss/postcss/tree/master/docs) .md directly to the website.

**Comment by Grawl** [comment]
It's must be a heading “How to summon the devil” with the right link to a user guide on it.
