### ISSUE TITLE
[Page] API

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#71]
We need a page for visitors to look up API - We have to be smart here because there is a lot of documentation so we have to break it down into an anchor tag page. 

API: https://github.com/postcss/postcss/blob/master/docs/api.md 

**Please** read through our [contributing guidelines](https://github.com/postcss/postcss.org/blob/master/docs/content.md) before you start.

https://github.com/postcss/postcss.org/blob/master/content/docs/  (needs markdown file)

**Comment by marcustisater** [comment]
PostCSS 5.1 will be released next week. There is going to be a move with the [API.md](https://github.com/postcss/postcss/blob/master/docs/api.md) to JSDoc comments. 

There for links to `docs/api.md` will then return 404. We need to generate the API page for postcss.org by JSDoc.

**Comment by marcustisater** [comment]
I will see if I can get an basic page layout with minimal styling until Monday.

**Comment by marcustisater** [comment]
Related to https://github.com/postcss/postcss/issues/480

**Comment by marcustisater** [comment]
Sync from gitter

> I found some issues with JSDocs and current API.md, so JSDoc issue was delayed to the end of the week (or even later) But, for JSDoc API page we also need a good floating menu side menu with classes and methods links

**Comment by thangngoc89** [comment]
I implemented the sidebar thing [in my blog](https://github.com/thangngoc89/blog/blob/6b1be9f55464d532f3aa63da4f2f1c7a2454e2d1/web_modules/layouts/Post/Post.js#L185-L191). It also has a spy scroll and url's hash will be synced with the spy scroll.

See it in action [here](https://khoanguyen.me/react-component-voi-react-create-class/)

But there is a bug that I don't know how to fix it :( https://github.com/thangngoc89/blog/issues/59

**Comment by ai** [comment]
@thangngoc89 yeap, good example. But also we need a quick search in method.

**Comment by thangngoc89** [comment]
Should be easy to implement search function. Beware of the [bug from statinamic](https://github.com/MoOx/statinamic/issues/283).

**Comment by marcustisater** [comment]
Thanks for the update.

@thangngoc89: [That](https://khoanguyen.me/react-component-voi-react-create-class/) looks great and exactly what I had in mind. If you have time, PR is very much welcome for implementing the sidebar with spy scroll. I think we can keep it in the page component **for now**.

To sync gitter conversation between me and @ai I was a bit confused regarding the generated API page. It's not going to be generated as a markdown file so I'm a bit curious what format and tools that needs to make this work into the output. The generated process will be done through some CLI tool over at the postcss repo so we need a way to "sync/clone" that generated page to this repo and also keep it version controlled. 

Sorry for making it a little bit more confusing but I want everyone to be on the same path here. I think search function can wait for now until bug is resolved.

**Comment by thangngoc89** [comment]
@marcustisater I'm not familar with JSDoc. Are you planning on using JSDoc or others tool that can understand JSDoc syntax ? JSDoc have a [markdown plugin](http://usejsdoc.org/plugins-markdown.html).

btw, statinamic 0.9.0 will be decoupled from markdown engine. We called it the render engine now. It is a function that take a string and return HTML string. So you can use whatever render engine you like.

**Comment by marcustisater** [comment]
Thanks for info. Let's wait until @ai has figured out the [JSDoc comments ](https://github.com/postcss/postcss/issues/480)before we look into rendering it out on the website. I think JSDoc markdown plugin could be worth looking into.

**Comment by ai** [comment]
I added JSDoc for a half of classes. I think JSDoc will be finished on next week.

**Comment by marcustisater** [comment]
Great! I'll see if I can get up a page next week but I'm kind of busy with work at the moment :(
