### ISSUE TITLE
Performance budget

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss.org#74]
Inline with @MoOx [suggestion](https://github.com/postcss/postcss.org/issues/4#issuecomment-171454464) to break things out into smaller bite-sized issues, I wanted to pose the question here; should a [performance budget](https://timkadlec.com/2013/01/setting-a-performance-budget/) be set?

If so, I think there are two things that should be discuss, and decide upon, in this issue:

1. What is the budget?
2. What can be done to ensure the website is delivered to the user within that budget?

There are a few suggestions about how to go about deciding on a budget in the article I link to above. Regarding what can be done, here are a few starter questions:

1. Typography: The statinamic boilerplate [already makes use of](https://github.com/MoOx/statinamic/blob/master/boilerplate/web_modules/Layout/index.css#L82) system fonts. Should that approach carry on through to the final build and, as such, should web fonts only be used for display/heading elements as per [this suggestion](http://alistapart.com/article/back-to-the-future-in-2016#perez-cruz)? If custom fonts are used for display elements, how are they loaded (perhaps using the [CSS font loading API](http://blog.typekit.com/2015/12/16/better-font-events-with-the-native-font-loading-api/))? Lastly, do these decisions affect the proposed mock-ups in any way?

2. Graphics: @ai has [already mentioned](https://github.com/postcss/postcss.org/issues/4#issuecomment-169363495) lazy-loading graphics like the hero image. What else can be done? Again, these decisions affect the proposed mock-ups?

3. Client-side scripts: as mentioned in [this tweet](https://twitter.com/pepelsbey_/status/687771818795622402), the current client-side JavaScript is 1mb. What can be done to reduce this? I understand that the REPL page will require client-side scripts, and so can we lazy-load those on only the required pages? Can rest of the site by statically generated?

Any more?

Once the budget is decided upon, it might be worth breaking each of the three areas above into their own issues and closing this one.

Ref: this issue touches on the issues: #3, #4 and #12.

**Comment by mxstbr** [comment]
We might need one, not a bad idea.

Re your questions:

1) We can always use FontFaceObserver to load web fonts after everything is rendered and usable if we were so inclined, but just using web save fonts is a nicer option.

2) Yeah, we will need some fallback for when the image hasn't loaded yet. Some sort of CSS gradient maybe?

3) The client side JavaScript file (`statinamic-client.js`) is 246 KB as per my Chrome network tab. No idea where the tweet got that number from.

<img width="411" alt="screen shot 2016-01-16 at 18 40 11" src="https://cloud.githubusercontent.com/assets/7525670/12373656/9d188f00-bc80-11e5-9c46-62971b51e2a2.png">

**Comment by marcustisater** [comment]
We definitely need to set a Performance Budget and look over the performance. I think we can start once we have a established theme from #4 to overlook what we have to deal with.

2. Yup, lazyload and fallback should be enough or CDN maybe? :wink:

3. I think he included the JSON files in his calculations, unesercery tweet and should be ignored... :angry:     

Great article btw, thanks for the read @jeddy3 - btw great job with creating issues :+1:

**Comment by ai** [comment]
File size is not important, requests count is a big deal.

So, if we have 300 KB for JS and 300 KB for CSS with all images inlined, we are good.

I can take care of load time optimization after we will make first iteration. I like this things :-D

**Comment by jeddy3** [comment]
> So, if we have 300 KB for JS and 300 KB for CSS with all images inlined, we are good.

Sounds like we have a budget :)

Shall I close this issue, and create a separate issue for the typography (to garner feedback from the designers etc) and another for ideas about load-time optimisations (including optimising the loading of graphics)?

(I won't create one for the the client-side script size as that's been dealt with here - thanks @mxstbr and @marcustisater. I should of checked it myself!)

**Comment by marcustisater** [comment]
Sounds perfect, go for it.

**Comment by jeddy3** [comment]
Done :)
