### ISSUE TITLE
homepage have a "refresh" issue

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss.org#77]
This is just this issue https://github.com/MoOx/statinamic/issues/61
I will handle this.

**Comment by marcustisater** [comment]
Yeah, I noticed that...

Great!

**Comment by MoOx** [comment]
statinamic@0.6.1 fix this issue.

You are on the 0.5.x version, not sure there is a big change to upgrade to 0.6 but that involves might upgrading to babel@6. No big deal.

Also, that might be done a bit later, maybe that can way for some statinamic breaking changes (eg: https://github.com/MoOx/statinamic/issues/83 and friends).

I can handle it now or later if you want.

**Comment by mxstbr** [comment]
I think you should be the one to decide @MoOx, you're the one with the roadmap of Statinamic in your head! What do you think?

**Comment by MoOx** [comment]
I think it's not urgent atm. So we can wait a few days until I handle some minor breaking changes. Then we will be able to upgrade everything. I can handle it, it will be quicker.

**Comment by mxstbr** [comment]
Alright, sounds good to me!

**Comment by marcustisater** [comment]
I agree, it's better to do everything in one round.

**Comment by marcustisater** [comment]
#94
