### ISSUE TITLE
Question: Content folder

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#78]
Quick question;

I am creating some pages for the website so it's easier for people to contribute with content when I can refer an markdown file in the issue. My question is - can we add more directories in the [content folder](https://github.com/postcss/postcss.org/tree/master/content) to make it more organized or should I just throw all the markdown files in there?

**Comment by marcustisater** [comment]
ping @mxstbr

**Comment by mxstbr** [comment]
Currently doing this, give me five minutes!

**Comment by marcustisater** [comment]
Thanks! 

Does every markdown file have the option to choose a layout template like Page, Landing-page etc?...

**Comment by mxstbr** [comment]
Yep, might have different templates for different sections of the content.

**Comment by marcustisater** [comment]
True, ok great.

**Comment by marcustisater** [comment]
This should be enough for me to create more from. Thank you.
