### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss.org#86]
Continuing to break [issues](https://github.com/postcss/postcss.org/issues/74) into smaller bite-sized chunks...

This issue is to garner everyone's—especially the designers—thoughts on the typography for the website.

I think the main consideration is whether to use [System UI](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/), [web-safe](http://www.mightymeta.co.uk/resources/web-safe-fonts-cheat-sheet-v3b.png), [web fonts](https://github.com/typekit/webfontloader), or a combination of those three.

Notes:

* The statinamic boilerplate [already makes use of](https://github.com/MoOx/statinamic/blob/master/boilerplate/web_modules/Layout/index.css#L82) system UI fonts. 
* Perhaps only using web fonts for display/heading elements as per [this suggestion](http://alistapart.com/article/back-to-the-future-in-2016#perez-cruz)?
* Discussing what effect these decisions have on achieving the [performance budget of 600k](https://github.com/postcss/postcss.org/issues/74#issuecomment-172246663).
* Discussing what effect these decisions have on the proposed mocks-up in #4.

@mxstbr @marcustisater have voiced a preference for web-safe fonts (refs: https://github.com/postcss/postcss.org/issues/74#issuecomment-172235392 & https://github.com/postcss/postcss.org/issues/74#issuecomment-172244110).

Quick disclaimer... over at `stylelint`, we're hoping to use—a little later down the line—statinamic for the http://stylelint.io website, and so we're hoping to follow the well-thought-out path trodden by you guys here :)

**Comment by mxstbr** [comment]
@MoOx you're going to like this disclaimer. :wink: 

Thanks for opening this issue, I'll repost my opinion here for easier reading:

> We can always use FontFaceObserver to load web fonts after everything is rendered and usable if we were so inclined, but just using web save fonts is the nicer option.

**Comment by ai** [comment]
If we have oly one custom font, it will be better to just inline it to CSS. We should reduce requests, not a size.

Especially, because font changing is not good for reading process ;).

**Comment by MoOx** [comment]
For my concern, I think typos for heading might be "sweet", but optional.
I am considering adding more good practices in statinamic boilerplate, so I will follow this issue :)

**Comment by marcustisater** [comment]
We are going to be using two webfonts. [Fira Sans](https://www.google.com/fonts/specimen/Fira+Sans) and [Merriweather](https://www.google.com/fonts/specimen/Merriweather)

@mxstbr - Would you mind adding these?

**Comment by marcustisater** [comment]
@jeddy3 - we are currently set to system ui fonts correct?

Designers implemented [Fira Sans](https://www.google.com/fonts/specimen/Fira+Sans) and [Merriweather](https://www.google.com/fonts/specimen/Merriweather) into the design.

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/12766453/ef60e06a-c9d1-11e5-9795-fa5e16322167.png)

Can someone explain what this font is? Is it just like a Mac specific global default font or some crap? I can't find it anywhere but it looks beautiful.

**Comment by jeddy3** [comment]
> @jeddy3 - we are currently set to system ui fonts correct?

That's right.

@corysimmons The site currently uses [system UI fonts](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/). So what you're seeing in your system's UI font e.g. if you're on OSX El Captain you're probably seeing San Francisco.

**Comment by corysimmons** [comment]
@jeddy3 Awesome, thanks. Didn't realize this was a thing.

**Comment by MoOx** [comment]
I originally left a comment (because this kind of font-family stack need to be explained https://github.com/postcss/postcss.org/search?utf8=%E2%9C%93&q=-apple-system&type=Code)

https://medium.com/@mwichary/system-shock-6b1dc6d6596f#.3io6q9rem

**Comment by marcustisater** [comment]
I added webfonts from GoogleFonts with [FontFaceObserver](https://github.com/bramstein/fontfaceobserver). That should be good enough, "fallback" is System UI fonts.
