### ISSUE TITLE
Load-time optimisations

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss.org#89]
Continuing to break issues into smaller bite-sized chunks... this issue is just about load-time optimisations.

@ai likes these optimisations and [has said](https://github.com/postcss/postcss.org/issues/74#issuecomment-172246663) he'd tackle it after the first iteration is done :)

Perhaps to help him out, everyone can jot down things they think could be included in that process. Here's a couple to get started:

1. Optimise SVG logs with [SVGO](https://github.com/svg/svgo)?
2. Optimise the hero image using the "[compressive images](https://www.filamentgroup.com/lab/compressive-images.html)" technique?
4. Optimizing the [critical rendering path](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/?hl=en)?

**Comment by ai** [comment]
Yeap, main idea of optimization is to inline all critical things (fonts, content/small images) and lazy load for all non critical things images.

postcss-inline-svg is good for inline images. Cssnano runs SVGO for all inlined images.

**Comment by ai** [comment]
But what we will do with browser caches, because we have no access to web server config in GH Pages?

Maybe we should use some CDN proxy for cache headers?

**Comment by marcustisater** [comment]
Quick notes:

* Sprites for the images or icon font if designers has thoughts of implementing that
* 2. [mozjpeg](https://github.com/mozilla/mozjpeg ) might be worth looking into. What do you think @jeddy3 ?
* Is it worth looking into a CDN @jeddy3 ?

**Comment by MoOx** [comment]
I think a smart lazyloading react component can be easy to implement, by adding something in componentDidMount + a listener to scroll/resize. That said, to avoid the ugly "lazyload" effect (eg: image that appear after you scroll), it might be interesting to load images just before they came in the viewport.

**Comment by ai** [comment]
Loading on scroll is good for big sites with long lists.

In your case we should just split images to two parts: critical and non-critical. And load all non-critical just afrer `onload` event.

On main page non-critical JS will be for REPL, because PostCSS is not big (because of `source-map` package). Alll other JS and CSS can be packed into one `main.js` and `main.css`.

Docs and other pages can share one `app.js` and `app.css`, I think.

**Comment by MoOx** [comment]
Keep in mind that all pages are currently using a common js, to load pages using client side react rendering.
So yes I also think that we should lazyload (it's very easy using [webpack require.ensure()](https://webpack.github.io/docs/code-splitting.html) and transparent) stuff like the REPL.

**Comment by mxstbr** [comment]
Routes should all be chunked and loaded on demand using `require.ensure`, like so:

```JSX
<Route
  path="/"
  getComponent={(location, callback) => {
    require.ensure('./HomePage.jsx', function (require) {
      var HomePage = require('./HomePage.jsx');
      callback(null, HomePage);
    }, 'HomePage');
  }}
/>
```

Does Statinamic already do that @MoOx?

**Comment by MoOx** [comment]
By default, statinamic have one layout and load md files (json actually), so no it does not.
Anyway, I think having 2 or 3 layouts files is not a big deal compared to the entire chunk.

**Comment by thangngoc89** [comment]
This should be related https://github.com/MoOx/statinamic/issues/130

**Comment by marcustisater** [comment]
I will close this issue because most of this is already adressed or completed. 

Break this down into smaller issues if anything is missing.
