### ISSUE TITLE
Update Statinamic

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#94]
Update Statinamic to version 0.6.1+ once the minor changes are done as well

**Comment by marcustisater** [comment]
@MoOx - How is Statinamic looking? Do you need any help resolving issues? I would love to have the image solution for folders integrated into the update too.

**Comment by MoOx** [comment]
Bug is fixed in core. Assets have been improved, but I am working on the DX atm and a huge refactoring is in progress, I would like to finish before cuting a new release.
Are you "in a hurry"?

**Comment by marcustisater** [comment]
Awesome, no absolutely not. I am just looking for a quick status report and to check if you need any help with it. 

Thanks!

**Comment by thangngoc89** [comment]
I can help with this issue.

I'm learning about PostCSS so this is a good chance to get involved with the community. @MoOx it looks like next release has breaking changes. Will it be 1.0.0 or 0.7.0 ?

**Comment by marcustisater** [comment]
Statinamic is in another [repository](https://github.com/MoOx/statinamic). I'm sure @MoOx can assist you over there if he needs any help with something. Be on the lookout for `PR welcome` labels. 

If you would like to work on individual issues for [postcss.org](http://www.postcss.org), have a look [here](https://github.com/postcss/postcss.org/milestones/1.0). By helping @MoOx with Statinamic you are also contributing for PostCSS! :smile: 

Thanks for joining in.

**Comment by thangngoc89** [comment]
@marcustisater I'm helping @MoOx with statinamic at the moment (just look at statinamic's issues list https://github.com/MoOx/statinamic/issues)

**Comment by marcustisater** [comment]
Ok that's great! :metal:

**Comment by MoOx** [comment]
0.7 should land soon. Not ready for 1.0 yet (basic things still missing).

**Comment by marcustisater** [comment]
I'm thinking a public release on Friday the 19th for `postcss.org`. Is that doable for you guys?

**Comment by MoOx** [comment]
Having issues with the major upgrade because of babel recent update. Not sure that doable.

**Comment by thangngoc89** [comment]
I'll prepare a pr and waiting for release

**Comment by MoOx** [comment]
Major issue has been fixed, so I will handle some small things an cut a release asap.

**Comment by marcustisater** [comment]
Great to hear and if time cuts short, we can just move the deadline for [1.0](https://github.com/postcss/postcss.org/milestones/1.0)
