### ISSUE TITLE
Repository for OSD

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#96]
We had a discussion creating a new repository for the design part for postcss.org. I don't want to make the "final call" before we have discussed it. 

> The goals of this new repo would be to make a boilerplate for other designers to fork and design off of per page layout. So if we were to use this repo for that purpose, we would end up with 20+ sketch files alongside the website itself. I think approach could hurt the open nature of OSD, mainly because you should be able to fork quickly and iterate without any extra cruft. This might fall in line with your idea to do smaller PRs since we can selectively decide which forks are addressed in the org repo.

The way I see it

* + Easier maintenance and for new contributors to get started.
* - Confusing between repo collaborations. 
* -/+ We split one big repo into two parts

Suggestions:

1. Create a new repository named ex. `postcssorg-open-design`

2. Create a new directory `design` in this repository with assets. 

I would like to make this decisions very quick and straight forward. Thoughts? 

OSD = Open Source Design

**Comment by okonet** [comment]
I think it might be confusing to have separate repos for basically the same thing. I vote for `design` directory.

**Comment by stephenway** [comment]
My vote is for a separate repo for the design using this boilerplate for open design https://github.com/stephenway/open-design-boilerplate

It is nice because you can diff each commit visually and designers can easily fork and iterate off it. So the main design repo would be mainly just the master layouts and guidelines for design practices. As we get new layouts defined, they can be added as PRs.

**Comment by okonet** [comment]
@stephenway I think PRs and designs diff are also possible within one repo. Or am I missing something?

**Comment by marcustisater** [comment]
That's what I'm scared of, right. If we have everything in this repository it can become very bloated and difficult to find the final cuts otherwise we can end up creating a very depth root of directories and files `/design/src/layout/final/...` - also files that are not relevant. This repository should be the "production/live" one including files that are not relevant to the final deployment feels somewhat unorganized.  

However.... I think we are also adding a extra step to this process by creating another repository. Is it worth it? That's my main concern.

**Comment by okonet** [comment]
I think you're overcomplicating matters. We'll never be able to have mockups in sync with the website and I personally think we should not even try. As soon as the design concept is approved I'd move to the HTML/CSS/JS phase and would work from there.

**Comment by stephenway** [comment]
@okonet What makes you think the mockups will never be in sync? 

The idea is that we make this a project for working with others. Your comments seem to only address your personal concerns with this workflow.

@marcustisater I think the long term benefits outweigh the needs of the few and that this will allow us to work faster as a team. Keeping the repo simple and focused will help guide the designer without extra cruft of the fronted code and documentation.

**Comment by okonet** [comment]
> What makes you think the mockups will never be in sync?

Speaking from my experience. And I also think web-designers should write code.

Once website is ready, the design will not be changed a lot (until a complete redesign) so I don't quite follow the effort to organize it so much. We'll end up with probably a few sketch files for design and lots of frontend code.

But I might be missing something here. Could somebody explain me how you see the process? Either way I'm totally fine with both solutions (one repo and 2 repos). Just think the overhead isn't worth it.

**Comment by MoOx** [comment]
> Once website is ready, the design will not be changed a lot (until a complete redesign) so I don't quite follow the effort to organize it so much.

Completely agree. People will make PR to update the website and the sketch files will likely be outof date really quickly.
I think it's a waste of time. We are mostly here CSS dev, so what about starting from a blank page and iterate on the code directly with PR accompagnied with screenshots (after a minimal start, but PNG/JPG I saw seems fine).

**Comment by ai** [comment]
> People will make PR to update the website and the sketch files will likely be outof date really quickly.

I agree with @MoOx. We should start from CSS. Anyway right now all designers known CSS. It is a simplier and faster right now. In future we could find better way if wwe really will have non-CSS designers (but why they will contribute to CSS tool? ;) ).

**Comment by marcustisater** [comment]
I am still stuck in between the middle after reading you're guys thoughts but I am going to make the final call and say that we will keep everything within this repository otherwise we will just keeping arguing for another 50 comments.  

With that being said, @stephenway you might have to rethink you're strategy of how you want to organize OSD in this repository , talk over gitter and maybe @okonet can join us if you would be interested in helping with that too?

**Comment by marcustisater** [comment]
Thanks for everyones quick input btw. I think the majority would either way lean towards option number duo.
