### ISSUE TITLE
Requirements for Layout Contribution

### ISSUE THREAD

**Issue by stephenway** [postcss/postcss.org#97]
Now that we have a solid direction on design and contribution path, it seems that we need to flesh out the requirements.

* First off, we need @okonet to upload his design to Zeplin and invite members to the project. #98
* After that we need to get the front-end coded into this project.
* At this point we will need to identify which pages need custom layouts vs basic articles.
* Assign each custom layout as 'help needed'.

**Comment by marcustisater** [comment]
Great breakdown. Here are some of my notes.

* Everything from Zeplin should try to be reference in issues, tasks such as "Create the main-navigation" etc.. I will help with that once the design is up. 

* We should investigate how we are going to break down individual page layout as mentioned. The way I see it from the content point of view is that we have an "landing page", and single "page" with sidebar navigation for subpages. 

Yes, we definitely have to break down all the custom layouts.

**Comment by marcustisater** [comment]
Remember that every page is already in a issue form to remind. This is a good reminder to look at things that are "custom layouts" such as the plugin page.

https://github.com/postcss/postcss.org/issues/83

**Comment by marcustisater** [comment]
@stephenway - Would you mind If I create some issues for the custom layouts that needs design or would you like to organize that?

**Comment by stephenway** [comment]
If you think you know what layouts we need, by all means, but otherwise we should identify which pages need custom.

**Comment by marcustisater** [comment]
Good point, I know a few pages that would defently need to be custom but you are correct. I will sit down this weekend to really go through it all. Thanks.
