### ISSUE TITLE
Zeplin

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#98]
@okonet can you upload the mockup to a zeplin account? It would be easier to communicate the spec of the design for those are coding it. 

https://zeplin.io/

**Comment by stephenway** [comment]
#97

**Comment by marcustisater** [comment]
Can we make it public?

**Comment by okonet** [comment]
I've created an account and exported the mockup there (https://zpl.io/3S8HT). I could only invite @marcustisater and @mxstbr since others don't share their emails on GitHub. TBH I'd prefer the repository owner (@marcustisater) to create a postcss.com account so I can move the ownership there.

**Comment by okonet** [comment]
I think this is a public one: https://scene.zeplin.io/project/56a0b62267a6ad3125f53fd1

**Comment by marcustisater** [comment]
Yup seems fair, I can create one.

**Comment by marcustisater** [comment]
You can pass the ownership to my personal account and I'll talk with Audrey about an postcss.org account.

I will update some documentation tonight with an design directory together with @stephenway boilerplate.

Thank you for the upload.

**Comment by okonet** [comment]
I think you have to accept my invitation before I can transfer.

**Comment by stephenway** [comment]
Zeplin applied the plan to my account, so I can host this and invite others.

**Comment by marcustisater** [comment]
Oh, yeah I totally forgot. We got a free plan from Zeplin for this project right. Sorry.

Yeah, go ahead and invite.

**Comment by marcustisater** [comment]
Can you add the public url once it's up to  https://github.com/postcss/postcss.org/blob/master/design/README.md

**Comment by marcustisater** [comment]
Can we please get this up as soon as possible? It's all very confusing what sketch we are forming.

**Comment by stephenway** [comment]
https://zpl.io/TJT9K5

**Comment by Vall3y** [comment]
@stephenway This doesn't seem public. I get an error saying I am not invited

**Comment by stephenway** [comment]
Sorry @Vall3y looks like I shared the wrong link. This is more public https://scene.zeplin.io/project/56a3fb9180974a77015a1c2b

**Comment by marcustisater** [comment]
Great :+1: 

@okonet - can you upload the latest sketch file to Zepplin and repo? Thanks!

**Comment by okonet** [comment]
I dont' think the invite for Zipplin worked for me. I can't see the project so I can't export the latest design to it.

**Comment by okonet** [comment]
Can you also add me as a maintainer otherwise I must go throught PR each time.

**Comment by marcustisater** [comment]
It says on the member list that you are on pending invitation, let me see if I can reinvite you otherwise @stephenway will have to do that. 

Yeah, I will add you asap.

**Comment by marcustisater** [comment]
Did you manage to sign up? It says you are on the list.

**Comment by okonet** [comment]
No. It doesn't show me the project. Can you send me invite to `andrey@okonet.ru` please?

**Comment by marcustisater** [comment]
Alright, that's wired. I invite you're new e-mail adress, see if that works out for you.

**Comment by okonet** [comment]
This worked. Please remove my other (gmail) address. I didn't try to commit any changes yet. Not sure if I have enough rights (as a non-admin).

**Comment by marcustisater** [comment]
@stephenway can you add @okonet as admin for Zeplin?

**Comment by stephenway** [comment]
@marcustisater @okonet Done, everyone is admin again.
